//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using DespatchWeb.EntityClasses;

namespace DespatchWeb
{
	/// <summary>Class which represents the DataContext for the project / group 'DespatchWeb'</summary>
	public partial class DespatchWebDataContext : DbContext
	{
		partial void OnModelCreatingComplete();
	
		/// <summary>Saves all changes made in this context to the database.</summary>
		/// <returns>The number of state entries written to the database.</returns>
		/// <remarks>This method will automatically call <see cref="M:Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges" /> to discover any
		/// changes to entity instances before saving to the underlying database. This can be disabled via <see cref="P:Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.AutoDetectChangesEnabled" /></remarks>
		public override int SaveChanges()
		{
			var namesOfChangedReadOnlyEntities = this.ChangeTracker.Entries().Where(e => e.Metadata.IsReadOnly() && e.State != EntityState.Unchanged).Select(e => e.Metadata.Name).Distinct().ToList();
			if(namesOfChangedReadOnlyEntities.Any())
			{
				throw new InvalidOperationException($"Attempted to save the following read-only entitie(s): {string.Join(",", namesOfChangedReadOnlyEntities)}");
			}
			return base.SaveChanges();
		}
	
		/// <summary>Override this method to further configure the model that was discovered by convention from the entity types
		/// exposed in <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> properties on your derived context. The resulting model may be cached
		/// and re-used for subsequent instances of your derived context.</summary>
		/// <param name="modelBuilder">The builder being used to construct the model for this context. Databases (and other extensions) typically
		/// define extension methods on this object that allow you to configure aspects of the model that are specific
		/// to a given database.</param>
		/// <remarks>If a model is explicitly set on the options for this context (via <see cref="M:Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.UseModel(Microsoft.EntityFrameworkCore.Metadata.IModel)" />)
		/// then this method will not be run.</remarks>
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			new DespatchWebModelBuilder().BuildModel(modelBuilder);
			OnModelCreatingComplete();
		}



		/// <summary>Gets an object query for the entity set 'DesQryAllJobType', containing entity type 'DesQryAllJobType'</summary>
		public DbSet<DesQryAllJobType> DesQryAllJobTypes { get; set; } 
		/// <summary>Gets an object query for the entity set 'DesQrySupportEventsCustomerAndCourier', containing entity type 'DesQrySupportEventsCustomerAndCourier'</summary>
		public DbSet<DesQrySupportEventsCustomerAndCourier> DesQrySupportEventsCustomerAndCouriers { get; set; } 
		/// <summary>Gets an object query for the entity set 'DeswebQryDespatch', containing entity type 'DeswebQryDespatch'</summary>
		public DbSet<DeswebQryDespatch> DeswebQryDespatches { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblClient', containing entity type 'TblClient'</summary>
		public DbSet<TblClient> TblClients { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblClientContact', containing entity type 'TblClientContact'</summary>
		public DbSet<TblClientContact> TblClientContacts { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblClientContactInternetPermission', containing entity type 'TblClientContactInternetPermission'</summary>
		public DbSet<TblClientContactInternetPermission> TblClientContactInternetPermissions { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblCourier', containing entity type 'TblCourier'</summary>
		public DbSet<TblCourier> TblCouriers { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblDespatchView', containing entity type 'TblDespatchView'</summary>
		public DbSet<TblDespatchView> TblDespatchViews { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblInternetPermission', containing entity type 'TblInternetPermission'</summary>
		public DbSet<TblInternetPermission> TblInternetPermissions { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblJob', containing entity type 'TblJob'</summary>
		public DbSet<TblJob> TblJobs { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblJobLeaveNotHome', containing entity type 'TblJobLeaveNotHome'</summary>
		public DbSet<TblJobLeaveNotHome> TblJobLeaveNotHomes { get; set; } 
		/// <summary>Gets an object query for the entity set 'TblUndeliverableLocation', containing entity type 'TblUndeliverableLocation'</summary>
		public DbSet<TblUndeliverableLocation> TblUndeliverableLocations { get; set; } 
		/// <summary>Gets an object query for the entity set 'TucClient', containing entity type 'TucClient'</summary>
		public DbSet<TucClient> TucClients { get; set; } 
		/// <summary>Gets an object query for the entity set 'TucClientContact', containing entity type 'TucClientContact'</summary>
		public DbSet<TucClientContact> TucClientContacts { get; set; } 
		/// <summary>Gets an object query for the entity set 'TucEvent', containing entity type 'TucEvent'</summary>
		public DbSet<TucEvent> TucEvents { get; set; } 
		/// <summary>Gets an object query for the entity set 'TucJobItem', containing entity type 'TucJobItem'</summary>
		public DbSet<TucJobItem> TucJobItems { get; set; } 
		/// <summary>Gets an object query for the entity set 'TucJobStatus', containing entity type 'TucJobStatus'</summary>
		public DbSet<TucJobStatus> TucJobStatuses { get; set; } 
		/// <summary>Gets an object query for the entity set 'TucJobType', containing entity type 'TucJobType'</summary>
		public DbSet<TucJobType> TucJobTypes { get; set; } 
		/// <summary>Gets an object query for the entity set 'TucSuburb', containing entity type 'TucSuburb'</summary>
		public DbSet<TucSuburb> TucSuburbs { get; set; } 
		/// <summary>Gets an object query for the entity set 'UvwBookingToday', containing entity type 'UvwBookingToday'</summary>
		public DbSet<UvwBookingToday> UvwBookingTodays { get; set; } 
}
}
