// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class DeliveryPhoto
{
    public int DeliveryPhotoId { get; set; }

    public int JobId { get; set; }

    public byte[] Photo { get; set; }
}