// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class DES_qryTruckCourierStatusResult
    {
        public int ucjbCourierID { get; set; }
        public string CourierCode { get; set; }
        public string FirstName { get; set; }
        public int? MaxPallets { get; set; }
        public double? MaxPayLoad { get; set; }
        public int CurrentPallets { get; set; }
        public double CurrentWeight { get; set; }
        public int? availablePallets { get; set; }
        public double? availableWeight { get; set; }
    }
}
