// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
    public partial class DesQryAllJobType
    {
        public int JobTypeId { get; set; }
        public string Name { get; set; }
    }
}