// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
    public partial class TblDespatchView
    {
        public int DespatchViewId { get; set; }
        public string Name { get; set; }
        public string WhereCondition { get; set; }
        public DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public string Notes { get; set; }
        public bool? ShowOnDespatch { get; set; }
        public bool? ShowOnAssistDespatch { get; set; }
        public bool? ShowOnJobFollowup { get; set; }
    }
}