// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblInternetPermission
{
    public int InternetPermissionId { get; set; }

    public string Name { get; set; }

    public string SystemName { get; set; }

    public bool HideWhenInactive { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public bool AssignToNewContacts { get; set; }

    public virtual ICollection<TblClientContactInternetPermission> TblClientContactInternetPermissions { get; set; } = new List<TblClientContactInternetPermission>();
}