// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucEventType
{
    public int UcetId { get; set; }

    public string UcetGroup { get; set; }

    public string UcetName { get; set; }
}