<Project Sdk="Microsoft.NET.Sdk.Web">
  <Target Name="NpmBuild" BeforeTargets="Build">
    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)" />
  </Target>
  <PropertyGroup Label="Globals">
  </PropertyGroup>
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
  </PropertyGroup>

  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="bundleconfig.json" />
    <Content Remove="compilerconfig.json" />
    <Content Remove="wwwroot\css\udispatch.min.css" />

  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Remove="wwwroot\app\types.min.js" />
    <Content Remove="wwwroot\app\version-url.js" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="compilerconfig.json" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular\angular-material.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular\angular.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular-confirm\angular-confirm.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular-confirm\angular-confirm.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\resizable\angular-resizable.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\resizable\angular-resizable.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\.bower.json" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.min.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.eot" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\npm.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\LICENSE" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-date-dialog\edit-date-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-date-dialog\edit-date-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-date-dialog\edit-date-dialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwide.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwide.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebook.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebook.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\top-bar\top-bar.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\top-bar\top-bar.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\autoCompleteDialog\autoCompleteDialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\autoCompleteDialog\autoCompleteDialogController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\autoCompleteDialog\autoCompleteDialogController.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\selectDialog\selectDialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\selectDialog\selectDialogController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\selectDialog\selectDialogController.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\sendMessageDialog\sendMessageDialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\sendMessageDialog\sendMessageDialogController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\gpsForm\gpsForm.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\gpsForm\gpsFormController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\Nationwide\tpls\map.tpl" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="wwwroot\app\components\common\side-nav\side-nav.template.html" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Helpers\DynamicLinqParser.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bundleconfig.json" />
    <None Include="compilerconfig.json" />
    <None Include="efpt.config.json.user" />
    <None Include="wwwroot\app\components\common\dispatch-map\dispatch-map.directive.js" />
    <None Include="wwwroot\app\components\common\dispatch-map\dispatch-map.styles.less" />
    <None Include="wwwroot\app\components\common\dispatch-map\dispatch-map.template.html" />
    <None Include="wwwroot\app\components\common\side-nav\side-nav.directive.js" />
    <None Include="wwwroot\app\components\common\side-nav\side-nav.template.html" />
    <Page Include="wwwroot\app\components\overview\open-jobs\open-jobs.controller.js" />
    <None Include="wwwroot\app\components\overview\services\overview-filters.service.js" />
    <Page Include="wwwroot\app\components\dialogs\date-range-dialog\date-range-dialog.controller.js" />
    <None Include="wwwroot\app\components\dialogs\map-dialog\map-dialog.controller.js" />
    <None Include="wwwroot\app\components\dialogs\map-dialog\map-dialog.template.html" />
    <None Include="wwwroot\app\components\dialogs\edit-parcel-dimensions-dialog\edit-parcel-dimensions-dialog.controller.js" />
    <None Include="wwwroot\app\components\dialogs\edit-parcel-dimensions-dialog\edit-parcel-dimensions-dialog.html" />
    <None Include="wwwroot\app\components\dialogs\feature-in-development-dialog\feature-in-development-dialog.controller.js" />
    <None Include="wwwroot\app\components\dialogs\feature-in-development-dialog\feature-in-development-dialog.html" />
    <None Include="wwwroot\app\components\overview\overview.less" />
    <None Include="wwwroot\css\udispatch.less" />
    <None Include="wwwroot\lib\material-time-picker\md-time-picker.css" />
    <None Include="wwwroot\lib\material-time-picker\md-time-picker.js" />
    <None Include="wwwroot\lib\material-time-picker\md-time-picker.min.css" />
    <None Include="wwwroot\lib\material-time-picker\md-time-picker.min.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\lib\modernizr.touch.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.css" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.css.map" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.min.css" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.min.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\src\mfb-directive.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\src\mfb-directive.min.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.DataProtection.SSM" Version="3.2.1" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.2" />
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.404.7" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.7.400.35" />
    <PackageReference Include="AWSSDK.SSO" Version="3.7.400.35" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="EntityFrameworkCore.UseRowNumberForPaging" Version="0.5.0" />
    <PackageReference Include="ExcelDataReader" Version="3.7.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
    <PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
  </ItemGroup>
  <ItemGroup>
    <TypeScriptCompile Include="wwwroot\app\components\common\job-details\job-details.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\job-details\job-details.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\contants.ts" />
    <TypeScriptCompile Include="wwwroot\app\index.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\app-config.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\courier.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\job.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\open-job-options.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\state-info.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\materialTheme.ts" />
    <TypeScriptCompile Include="wwwroot\app\routes.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\config.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\dispatch-job.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\getUsStates.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\greeting.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\index.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\open-job-dispatch.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\toastr.service.ts" />
  </ItemGroup>
</Project>
