<Project Sdk="Microsoft.NET.Sdk.Web">
  <Target Name="NpmBuild" BeforeTargets="Build">
    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)" />
  </Target>
  <PropertyGroup Label="Globals">
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
  </PropertyGroup>

  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

	<PropertyGroup>
		<!-- Makes the TypeScript compilation task a no-op -->
		<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
	</PropertyGroup>
	
  <ItemGroup>
    <Content Remove="bundleconfig.json" />
    <Content Remove="compilerconfig.json" />
    <Content Remove="wwwroot\app\interfaces\heremaps-autocomplete.interfaces.ts" />
    <Content Remove="wwwroot\css\udispatch.min.css" />

  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Remove="wwwroot\app\types.min.js" />
    <Content Remove="wwwroot\app\version-url.js" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="compilerconfig.json" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular\angular-material.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular\angular.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular-confirm\angular-confirm.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\angular-confirm\angular-confirm.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\resizable\angular-resizable.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\resizable\angular-resizable.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\.bower.json" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-theme.min.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.eot" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\fonts\glyphicons-halflings-regular.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\npm.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\LICENSE" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-date-dialog\edit-date-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-date-dialog\edit-date-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-date-dialog\edit-date-dialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\app.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\CS\csService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-event-dialog\add-event-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-notes-dialog\add-notes-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\add-pallet-dialog\add-pallet-dialog.Controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\additional-services-dialog\additional-services-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\create-job-dialog\create-job-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-address-dialog\edit-address-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\job-file-upload-dialog\job-file-upload.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\select-dialog\select-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\send-message-dialog\send-message-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\home\homeService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\Map.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwide.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwide.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\Nationwide\nationwideService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookControl.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebook.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebook.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookService.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\components\prebooks\prebookService.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\filters.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\label.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\map.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\mapLabels.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\dispatch-job.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\greeting.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\job-detail.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\loading.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\rate-job.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\services\toastr.service.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\types.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\version.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\top-bar\top-bar.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\top-bar\top-bar.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\autoCompleteDialog\autoCompleteDialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\autoCompleteDialog\autoCompleteDialogController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\autoCompleteDialog\autoCompleteDialogController.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\selectDialog\selectDialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\selectDialog\selectDialogController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\selectDialog\selectDialogController.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\directives\auto-resize-table.directive.min.js.map" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\sendMessageDialog\sendMessageDialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\sendMessageDialog\sendMessageDialogController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\gpsForm\gpsForm.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\gpsForm\gpsFormController.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\Nationwide\tpls\map.tpl" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\dispatch-map\services\marker.factory.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\home\services\job-table.service.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\ui-router\angular-ui-router.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\ui-router\ct-ui-router-extras.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\fonts\glyphicons-halflings-regular.eot" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\fonts\glyphicons-halflings-regular.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\fonts\glyphicons-halflings-regular.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\fonts\glyphicons-halflings-regular.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\dist\fonts\glyphicons-halflings-regular.woff2" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\Nationwide\services\nationwide-layout.service.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\add-notes-dialog\add-notes-dialog.controller.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\add-notes-dialog\add-notes-dialog.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\prebooks\partials\preBookDetail.html" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\prebooks\prebook.service.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\warning-card\warning-card.component.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\common\warning-card\warning-card.template.html" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\autocomplete\angular-auto-complete.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\autocomplete\angular-auto-complete.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\add-pallet-dialog\add-pallet-dialog.controller.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\pickdate\angular-pickadate.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\pickdate\angular-pickadate.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\pickdate\angular-pickadate.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-parcel-dimensions-dialog\parcel-visuailzation\parcel-visualization.component.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-parcel-dimensions-dialog\parcel-visuailzation\parcel-visualization.styles.less" />
    <_ContentIncludedByDefault Remove="wwwroot\app\components\dialogs\edit-parcel-dimensions-dialog\parcel-visuailzation\parcel-visualization.template.html" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="wwwroot\app\components\common\side-nav\side-nav.template.html" />
  </ItemGroup>
  <ItemGroup>
    <None Include="efpt.config.json.user" />
    <None Include="wwwroot\app\components\common\dispatch-map\dispatch-map.styles.less" />
    <None Include="wwwroot\app\components\common\dispatch-map\dispatch-map.template.html" />
    <None Include="wwwroot\app\components\common\side-nav\side-nav.template.html" />
    <None Include="wwwroot\app\components\dialogs\map-dialog\map-dialog.template.html" />
    <None Include="wwwroot\app\components\dialogs\feature-in-development-dialog\feature-in-development-dialog.html" />
    <None Include="wwwroot\css\udispatch.less" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\lib\modernizr.touch.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.css" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.css.map" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.min.css" />
    <None Include="wwwroot\lib\ng-material-floating-button\mfb\dist\mfb.min.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\src\mfb-directive.js" />
    <None Include="wwwroot\lib\ng-material-floating-button\src\mfb-directive.min.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.DataProtection.SSM" Version="3.5.0" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.2" />
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.416.9" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.7.401.82" />
    <PackageReference Include="AWSSDK.SSO" Version="3.7.400.133" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="ExcelDataReader" Version="3.7.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
    <PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
  </ItemGroup>
  <ItemGroup>
    <TypeScriptCompile Include="wwwroot\app\components\base-controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\job-details\job-details.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\pod-photo-viewer\pod-photo-viewer.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\side-nav\side-nav.component.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\side-nav\side-nav.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\sticky-notes\sticky-notes.component.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\task-item-component\task-item.component.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\common\task-item-component\task-item.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\add-event-dialog\add-event-dialog.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\agent-info-dialog\agent-info-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\agent-info-dialog\agent-info-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\auto-complete-dialog\auto-complete-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\flight-agent-conformation-dialog\flight-agent-confirmation-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\flight-agent-conformation-dialog\flight-agent-conformation-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\flight-agent-conformation-dialog\flight-agent-conformation-dialog.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\flight-details-dialog\flight-details-dialog.component.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\flight-details-dialog\flight-details-dialog.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\flight-details-dialog\flight-details-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\truck-courier-status-dialog\truck-courier-status-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\jobSearch\enums\podSearchResponse.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\jobSearch\jobSearch.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\add-event-dialog\add-event-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\add-event-dialog\add-event-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\additional-services-dialog\additional-services-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\additional-services-dialog\additional-services-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\create-job-dialog\create-job-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\date-range-dialog\date-range-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\edit-address-dialog\edit-address-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\edit-address-dialog\edit-address-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\edit-parcel-dimensions-dialog\edit-parcel-dimensions-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\edit-parcel-dimensions-dialog\edit-parcel-dimensions-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\feature-in-development-dialog\feature-in-development-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\feature-in-development-dialog\feature-in-development-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\inter-courier-charge-dialog\inter-courier-charge-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\job-file-upload-dialog\job-file-upload-dialog.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\job-file-upload-dialog\job-file-upload-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\job-file-upload-dialog\job-file-upload.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\note-management-dialog\note-management-dialog.component.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\note-management-dialog\note-management.dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\price-breakdown-dialog\price-breakdown-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\price-breakdown-dialog\price-breakdown-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\select-dialog\select-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\select-dialog\select-dialog.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\send-message-dialog\send-message-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\auto-complete-dialog\auto-complete-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\create-job-dialog\create-job-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\date-range-dialog\date-range-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\edit-date-time-dialog\edit-date-time-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\map-dialog\map-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\dialogs\send-message-dialog\send-message-dialog.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\home\home.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\home\home.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\Nationwide\enums\JobDataType.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\Nationwide\enums\NationwideBoxes.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\Nationwide\nationwide.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\Nationwide\nationwide.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\overview\mega-map\mega-map.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\overview\mega-map\mega-map.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\overview\open-jobs\open-jobs.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\overview\overview.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\overview\overview.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\overview\overview.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\overview\services\overview-filters.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\recurringJobs\recurringJobs.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\recurringJobs\recurringJobs.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\task-dashboard\enums\status-filter.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\task-dashboard\enums\view-mode.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\task-dashboard\task-calendar-view\task-calendar-view.component.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\task-dashboard\task-calendar-view\task-calendar-view.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\task-dashboard\task-dashboard.controller.ts" />
    <TypeScriptCompile Include="wwwroot\app\components\task-dashboard\task-dashboard.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\contants.ts" />
    <TypeScriptCompile Include="wwwroot\app\directives.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\app-pages.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\dangerous-goods.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\days-of-week.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\event-type.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\file-upload-type.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\frequency.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\holiday-delivery-options.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\job-internal-status.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\job-note-type.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\job-property.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\job-status.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\enums\late-event-type.enum.ts" />
    <TypeScriptCompile Include="wwwroot\app\filters.ts" />
    <TypeScriptCompile Include="wwwroot\app\functions\countSubJobs.ts" />
    <TypeScriptCompile Include="wwwroot\app\functions\getDangerousGoodsClassName.ts" />
    <TypeScriptCompile Include="wwwroot\app\functions\getJobTableRowClass.ts" />
    <TypeScriptCompile Include="wwwroot\app\functions\greetUser.ts" />
    <TypeScriptCompile Include="wwwroot\app\functions\isFlightJob.ts" />
    <TypeScriptCompile Include="wwwroot\app\functions\sortRelatedJobs.ts" />
    <TypeScriptCompile Include="wwwroot\app\functions\usStates.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\app-config.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\apiConfig.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\context-menu-option.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\courier.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\dfrnt-page-view-model.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\dialog-result.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\event-group-view-model.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\event-interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\heremaps-autocomplete.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\hereMapsAppConfig.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\job-field.types.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\job-list-response.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\job.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\layout.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\open-job-options.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\paginated-response.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\requests.interfaces.ts" />
    <TypeScriptCompile Include="wwwroot\app\interfaces\state-info.interface.ts" />
    <TypeScriptCompile Include="wwwroot\app\materialTheme.ts" />
    <TypeScriptCompile Include="wwwroot\app\routes.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\address-lookup.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\config.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\dispatch-executor.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\job-add-stop.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\job-context-menu.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\notes.service.ts" />
    <TypeScriptCompile Include="wwwroot\app\services\tasks.service.ts" />
    <TypeScriptCompile Include="wwwroot\types\html.d.ts" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\app\components\dialogs\event-group-dialog\" />
    <Folder Include="wwwroot\dist\" />
  </ItemGroup>
</Project>
