// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class AccessorialChargeGroupMember
{
    public int AccessorialChargeGroupMemberId { get; set; }

    public int AccessorialChargeGroupId { get; set; }

    public int AccessorialChargeId { get; set; }

    public int DisplayOrder { get; set; }

    public bool AlwaysApply { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public virtual AccessorialCharge AccessorialCharge { get; set; }

    public virtual AccessorialChargeGroup AccessorialChargeGroup { get; set; }
}