// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class AccessorialChargeGroup
{
    public int AccessorialChargeGroupId { get; set; }

    public string GroupName { get; set; }

    public int? RateCardId { get; set; }

    public bool Active { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual ICollection<AccessorialChargeGroupMember> AccessorialChargeGroupMembers { get; set; } = new List<AccessorialChargeGroupMember>();

    public virtual ICollection<AirFreightRate> AirFreightRates { get; set; } = new List<AirFreightRate>();

    public virtual ICollection<TblBulkJob> TblBulkJobs { get; set; } = new List<TblBulkJob>();

    public virtual ICollection<TucJobArchive> TucJobArchives { get; set; } = new List<TucJobArchive>();

    public virtual ICollection<TucJobBooking> TucJobBookings { get; set; } = new List<TucJobBooking>();

    public virtual ICollection<TucJob> TucJobs { get; set; } = new List<TucJob>();
}