// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class AccessorialCharge
{
    public int AccessorialChargeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ChargeType { get; set; }

    public decimal? BaseRate { get; set; }

    public decimal? RatePerUnit { get; set; }

    public decimal? PercentageRate { get; set; }

    public decimal? MinimumCharge { get; set; }

    public decimal? MaximumCharge { get; set; }

    public decimal? MinimumQuantity { get; set; }

    public decimal? FreeAllowance { get; set; }

    public string ConditionalNote { get; set; }

    public int CalculationOrder { get; set; }

    public bool Active { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public int? UnitTypeId { get; set; }

    public int? FreeAllowanceUnitTypeId { get; set; }

    public string Tag { get; set; }

    public bool AvailableAtBooking { get; set; }

    public bool AvailableAtDispatch { get; set; }

    public bool AvailableAtCourier { get; set; }

    public virtual ICollection<AccessorialChargeGroupMember> AccessorialChargeGroupMembers { get; set; } = new List<AccessorialChargeGroupMember>();

    public virtual UnitType FreeAllowanceUnitType { get; set; }

    public virtual ICollection<JobAccessorialCharge> JobAccessorialCharges { get; set; } = new List<JobAccessorialCharge>();

    public virtual UnitType UnitType { get; set; }
}