// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace DespatchWeb.EntityClasses;

public partial class CargoFacility
{
    public int CargoFacilityId { get; set; }

    public int AirportId { get; set; }

    public int CarrierId { get; set; }

    public DateTime? OpeningTime { get; set; }

    public DateTime? ClosingTime { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual TblAirport Airport { get; set; }

    public virtual FlightCarrier Carrier { get; set; }
}