// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace DespatchWeb.EntityClasses
{
    public partial class DD_stpJob_InsertExceleratorResult
    {
    }
}
