// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class DD_stpGetCarrierFlightRateResult
    {
        public int? JobTypeID { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Speed { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [Column("Rate", TypeName = "money")]
        public decimal? Rate { get; set; }
        [Column("SaleRate", TypeName = "money")]
        public decimal? SaleRate { get; set; }
        [StringLength(250)]
        public string Availability { get; set; }
        [StringLength(250)]
        public string AvailabilityColour { get; set; }
        public DateTime? BookDate { get; set; }
        public int? Duration { get; set; }
        [Column("FlightRate", TypeName = "money")]
        public decimal? FlightRate { get; set; }
    }
}
