// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class DES_stpSettingsResult
    {
        public int SettingID { get; set; }
        public int MaxAutoLatePickupAlert { get; set; }
        public int MaxAutoLateDeliveryAlert { get; set; }
        public int EntryFormCount { get; set; }
        [StringLength(50)]
        public string SystemName { get; set; }
        [StringLength(10)]
        public string Version { get; set; }
        [StringLength(50)]
        public string ApplicationName { get; set; }
        [StringLength(50)]
        public string AdminEmail { get; set; }
        [StringLength(50)]
        public string ReportUserName { get; set; }
        [StringLength(50)]
        public string ReportPassword { get; set; }
        [StringLength(50)]
        public string ReportDomain { get; set; }
        public int ReportTimeout { get; set; }
        [StringLength(50)]
        public string DefaultDateRange { get; set; }
        [StringLength(100)]
        public string EnquiryEmail { get; set; }
        [StringLength(100)]
        public string SMTPServer { get; set; }
        [StringLength(100)]
        public string ContactUsEmailSubject { get; set; }
        public int DefaultPageDisplayNewsItems { get; set; }
        public int NewsPageDisplayItems { get; set; }
        public int CustomerFeedbackPageDisplayItems { get; set; }
        public int CustomerFeedbackPageDisplayCharacters { get; set; }
        [StringLength(100)]
        public string NewsImageDirectory { get; set; }
        [StringLength(100)]
        public string StaffImageDirectory { get; set; }
        [StringLength(100)]
        public string CommunicationFileDirectory { get; set; }
        [StringLength(100)]
        public string JoinOurTeamEmail { get; set; }
        [StringLength(100)]
        public string JoinOurTeamSubject { get; set; }
        [StringLength(100)]
        public string JobFeedbackSubject { get; set; }
        public int InternetJobChargeType { get; set; }
        public int InternetJobStaffID { get; set; }
        [StringLength(100)]
        public string InternetJobEmailSubject { get; set; }
        [StringLength(100)]
        public string InternetJobPOAEmail { get; set; }
        [StringLength(100)]
        public string InternetJobPOAEmailSubject { get; set; }
        public int NationwideAreaID { get; set; }
        [StringLength(100)]
        public string ToolTipImageDirectory { get; set; }
        public int DefaultPageDisplayJobItems { get; set; }
        public int InternetInvoiceReportID { get; set; }
        [StringLength(100)]
        public string InternetRoot { get; set; }
        [StringLength(100)]
        public string InternetClientDetailsEmail { get; set; }
        [StringLength(100)]
        public string InternetClientDetailsSubject { get; set; }
        [StringLength(100)]
        public string JoinOurTeamReplyFromEmail { get; set; }
        [StringLength(100)]
        public string JoinOurTeamReplySubject { get; set; }
        public string JoinOurTeamReplyMessage { get; set; }
        [StringLength(500)]
        public string JoinOurTeamReplyAttachment { get; set; }
        public byte[] FaxHeadLogo { get; set; }
        public byte[] LetterHeadLogo { get; set; }
        public int InternetRateScheduleReportID { get; set; }
        [StringLength(100)]
        public string JobDetailsReplyFromEmail { get; set; }
        [StringLength(100)]
        public string TrackAndTrackReplyFromEmail { get; set; }
        public int? RateGuideCommunicationTypeID { get; set; }
        [StringLength(500)]
        public string SQLErrorEmailAddress { get; set; }
        [StringLength(500)]
        public string SQLErrorMobile { get; set; }
        public DateTime Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public DateTime LastModified { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        public string Notes { get; set; }
        [StringLength(500)]
        public string ComposerExtrasPath { get; set; }
        [StringLength(2147483647)]
        public string StatementMessage { get; set; }
        [StringLength(500)]
        public string StatementReport { get; set; }
        [StringLength(10)]
        public string JournalEntityCode { get; set; }
        [StringLength(10)]
        public string JournalTransactionCode { get; set; }
        [StringLength(50)]
        public string JournalCreatedBy { get; set; }
        [StringLength(100)]
        public string JournalNarration { get; set; }
        [StringLength(100)]
        public string StatementEmailAddress { get; set; }
        public bool DespatchCheckContactHasEmail { get; set; }
        [StringLength(100)]
        public string GSTRegistrationNumber { get; set; }
        [StringLength(100)]
        public string CompanyBankNumber { get; set; }
        [StringLength(100)]
        public string CompanyAddress { get; set; }
        [StringLength(100)]
        public string ReportFolder { get; set; }
        [StringLength(100)]
        public string ReportServicesURL { get; set; }
        public int InternetStatementReportID { get; set; }
        public byte[] FaxHeadLogoSmall { get; set; }
        public int StatementCountPerGroup { get; set; }
        [StringLength(200)]
        public string StatementOutputDirectory { get; set; }
        public int StatementDelayBetweenGroups { get; set; }
        [StringLength(200)]
        public string MapRoot { get; set; }
        [StringLength(200)]
        public string DespatchUniqueEmailNotifyAddress { get; set; }
        public int? CurrentLoading { get; set; }
        public bool AutomaticUpdateLoading { get; set; }
        public string UncheckDirectEmailMessage { get; set; }
        [StringLength(200)]
        public string UncheckDirectEmailSubject { get; set; }
        [StringLength(200)]
        public string UncheckDirectEmailReply { get; set; }
        public int? BurstTheBubbleCourierID { get; set; }
        [StringLength(500)]
        public string RatesGuideImagePath { get; set; }
        [StringLength(200)]
        public string GoogleMapAPIKey { get; set; }
        public bool AllowPostingToOA { get; set; }
        [StringLength(100)]
        public string UTLogoImagePath { get; set; }
        [StringLength(100)]
        public string UTStyleSheetPath { get; set; }
        [StringLength(100)]
        public string UTAdditionalFileStyleDirectory { get; set; }
        [StringLength(100)]
        public string UTAdditionalFileImageDirectory { get; set; }
        public bool? UseGoogleAnalytics { get; set; }
        [StringLength(50)]
        public string GoogleAnalyticsCode { get; set; }
        public int? JobPackingReportID { get; set; }
        [StringLength(50)]
        public string DataComClientID { get; set; }
        public int? ParentJobCourierID { get; set; }
        [StringLength(50)]
        public string GoogleMapRoot { get; set; }
        [StringLength(200)]
        public string DPSPayRoot { get; set; }
        public int? InternetInvoiceSignatureReportID { get; set; }
        [Column("GSTRate", TypeName = "decimal(18,3)")]
        public decimal? GSTRate { get; set; }
        [StringLength(200)]
        public string AddressValidationURL { get; set; }
        [StringLength(50)]
        public string AddressValidationUser { get; set; }
        [StringLength(50)]
        public string AddressValidationPass { get; set; }
        public bool? AddressValidationActive { get; set; }
        [StringLength(200)]
        public string GoogleMapGeneratorRoot { get; set; }
        public bool? GoogleSMTPServerActive { get; set; }
        [StringLength(50)]
        public string GoogleSMTPServer { get; set; }
        [StringLength(50)]
        public string GoogleSMTPServerUser { get; set; }
        [StringLength(20)]
        public string GoogleSMTPServerPass { get; set; }
        public bool? AddressValidationDespatchActive { get; set; }
        public bool? AddressValidationActiveMercury { get; set; }
        public bool? GooglePlaceAutocompleteActive { get; set; }
        [StringLength(200)]
        public string GooglePlaceAutocompleteAPIKey { get; set; }
        [StringLength(200)]
        public string XeroServiceRefreshToken { get; set; }
        public DateTime? LastJobArchive { get; set; }
        public long? QuickBooksRealmId { get; set; }
        [StringLength(200)]
        public string QuickBooksRefreshToken { get; set; }
        public DateTime? AccountsStartDate { get; set; }
        [StringLength(50)]
        public string PpdCode { get; set; }
        [StringLength(50)]
        public string PpdDescription { get; set; }
        [StringLength(50)]
        public string PpdAppliedDescription { get; set; }
        public bool PpdGroupByLocation { get; set; }
        public int? AccountsClientDefaultId { get; set; }
        public int? InvoiceTemplateId { get; set; }
        [StringLength(500)]
        public string StatementBccEmailAddress { get; set; }
        [StringLength(500)]
        public string StatementDirectory { get; set; }
        public bool? StatementMessageIsHtml { get; set; }
        [StringLength(100)]
        public string OpenforceClientId { get; set; }
        [StringLength(2147483647)]
        public string OpenforceAccessKey { get; set; }
        [StringLength(100)]
        public string OpenforceActivationCode { get; set; }
        public int? AccountsMode { get; set; }
        [StringLength(50)]
        public string OpenforceApiKey { get; set; }
        [StringLength(50)]
        public string OpenforceClientGuid { get; set; }
        [StringLength(100)]
        public string ReceivableAccount { get; set; }
        [StringLength(200)]
        public string StatementSubject { get; set; }
        public DateTime? CourierServiceProcessed { get; set; }
        [StringLength(100)]
        public string InvoiceMemo { get; set; }
        public int? PaymentTermId { get; set; }
        public bool? InvoiceUseCalendarMonth { get; set; }
        [StringLength(50)]
        public string PpdItemCode { get; set; }
        public double? DefaultCourierPercentage { get; set; }
        [Column("DefaultCourierWithholdingTaxPercentage", TypeName = "decimal(8,2)")]
        public decimal? DefaultCourierWithholdingTaxPercentage { get; set; }
        [StringLength(50)]
        public string DefaultRevenueAccount { get; set; }
        [StringLength(50)]
        public string DefaultClass { get; set; }
        [StringLength(50)]
        public string DefaultItemCode { get; set; }
        [StringLength(50)]
        public string DefaultItemCodeFuel { get; set; }
    }
}
