// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class DES_qdfCourier_ClearListsResult
    {
        public int? CourierID { get; set; }
        [Column("#")]
        public string Hash { get; set; }
        public string NumberSign { get; set; }
        public int? DisplayOrder { get; set; }
        [StringLength(50)]
        public string Deliver { get; set; }
        public DateTime? DisplayOrderDESC { get; set; }
        public DateTime? DisplayOrderASC { get; set; }
        public bool? AutoDespatch { get; set; }
    }
}
