// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class DES_qryCourierCombo_ActiveResult
    {
        public int CourierID { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(101)]
        public string Name { get; set; }
        public byte DangerousGoods { get; set; }
        public DateTime? DGLicenseExpiry { get; set; }
    }
}
