// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using DespatchWeb.EntityClasses;

namespace DespatchWeb.EntityClasses
{
    public partial class DespatchContext
    {

        [DbFunction("EncryptJobIdReversible", "dbo")]
        public static string EncryptJobIdReversible(int? JobId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("UTL_fncClearList_Other", "dbo")]
        public IQueryable<UTL_fncClearList_OtherResult> UTL_fncClearList_Other()
        {
            return FromExpression(() => UTL_fncClearList_Other());
        }

        [DbFunction("UTL_fncClearListArea_Couriers", "dbo")]
        public IQueryable<UTL_fncClearListArea_CouriersResult> UTL_fncClearListArea_Couriers(int? ClearListAreaID, DateTime? CurrentDate)
        {
            return FromExpression(() => UTL_fncClearListArea_Couriers(ClearListAreaID, CurrentDate));
        }

        [DbFunction("UTL_fncJob_ExtraRate", "dbo")]
        public IQueryable<UTL_fncJob_ExtraRateResult> UTL_fncJob_ExtraRate(decimal? TotalWeight, int? Quantity, decimal? Cubic, int? TotalPallets, int? ExtraStopOffs, int? VehicleSizeID, bool? DangerousGoods, decimal? DryIceWeight, int? PickupWaitTime, int? DeliveryWaitTime, int? ExtraChargeID, bool? Holiday, bool? Afterhours, int? FromZoneCongestionID, int? ToZoneCongestionID, decimal? MFV, decimal? PPD, int? FuelSurchargeId, int? ClientID, DateTime? Date, string CubicList)
        {
            return FromExpression(() => UTL_fncJob_ExtraRate(TotalWeight, Quantity, Cubic, TotalPallets, ExtraStopOffs, VehicleSizeID, DangerousGoods, DryIceWeight, PickupWaitTime, DeliveryWaitTime, ExtraChargeID, Holiday, Afterhours, FromZoneCongestionID, ToZoneCongestionID, MFV, PPD, FuelSurchargeId, ClientID, Date, CubicList));
        }

        [DbFunction("UTL_fncJob_RawBaseToAmount", "dbo")]
        public static decimal? UTL_fncJob_RawBaseToAmount(int? JobID, decimal? RawBaseAmount)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("UTL_fncMFV_FAF_Rates", "dbo")]
        public static decimal? UTL_fncMFV_FAF_Rates(int? ClientID, DateTime? Date, int? SpeedID, int? VehicleSizeID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("UTL_fncS_GetNationwideService_RawPrice", "dbo")]
        public static decimal? UTL_fncS_GetNationwideService_RawPrice(int? ClientID, int? FromSuburbID, int? ToSuburbID, int? Speed, int? Size, double? Weight, int? Quantity, int? Type)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("UTL_fncSuburb_FromNameWithPostCode", "dbo")]
        public static int? UTL_fncSuburb_FromNameWithPostCode(string Suburb, int? SiteID, int? PostCode)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UTL_fncClearList_OtherResult>().HasNoKey();
            modelBuilder.Entity<UTL_fncClearListArea_CouriersResult>().HasNoKey();
            modelBuilder.Entity<UTL_fncJob_ExtraRateResult>().HasNoKey();
        }
    }
}
