// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class DespatchViewZoneGroup
{
    public int DespatchViewZoneGroupId { get; set; }

    public int DespatchViewId { get; set; }

    public int ZoneGroupId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual TblDespatchView DespatchView { get; set; }

    public virtual ZoneGroup ZoneGroup { get; set; }
}