// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DespatchWeb.EntityClasses;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DespatchWeb.EntityClasses
{
    public partial class DespatchContext
    {
        private IDespatchContextProcedures _procedures;

        public virtual IDespatchContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DespatchContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDespatchContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class DespatchContextProcedures : IDespatchContextProcedures
    {
        private readonly DespatchContext _context;

        public DespatchContextProcedures(DespatchContext context)
        {
            _context = context;
        }

        public virtual async Task<List<DES_qryTruckCourierStatusResult>> DES_qryTruckCourierStatusAsync(string CourierID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "CourierID",
                    Size = 40,
                    Value = CourierID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<DES_qryTruckCourierStatusResult>("EXEC @returnValue = [dbo].[DES_qryTruckCourierStatus] @CourierID = @CourierID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
