// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class DESWEB_qryPotentialCouriersResult
    {
        public int? CourierID { get; set; }
        public string Code { get; set; }
        public string Reason { get; set; }
        public int? RuleNumber { get; set; }
        public string FirstName { get; set; }
    }
}
