// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class DESWeb_qryCourierComboResult
    {
        public int ID { get; set; }
        public string Text { get; set; }
    }
}
