// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class DeswebQryDespatch
{
    public int? UcjbClientId { get; set; }

    public string UcjbNumber { get; set; }

    public DateTime? UcjbDispTime { get; set; }

    public DateTime? UcjbTime { get; set; }

    public DateTime? Putime { get; set; }

    public int UcjbId { get; set; }

    public int? UcjbCourierId { get; set; }

    public string CourierCode { get; set; }

    public string CourierName { get; set; }

    public string CourierMobile { get; set; }

    public string CourierSurname { get; set; }

    public string SuburbFrom { get; set; }

    public string SuburbTo { get; set; }

    public int? UcjbSpeed { get; set; }

    public DateTime? UcjbComplTime { get; set; }

    public int? UcjbDispId { get; set; }

    public bool UcjbAttention { get; set; }

    public short? UcjbPickUpFrom { get; set; }

    public int RegionFromId { get; set; }

    public int RegionToId { get; set; }

    public bool UcjbJobDone { get; set; }

    public bool UcjbPaged { get; set; }

    public DateTime? UcjbPagedTime { get; set; }

    public int? UcjbLatePick { get; set; }

    public int? UcjbLateDel { get; set; }

    public string PickupFromContact { get; set; }

    public string PickupFromPhone { get; set; }

    public string UcjbContact { get; set; }

    public string UcjbContactPhone { get; set; }

    public double? UcjbWeight { get; set; }

    public short? UcjbQty { get; set; }

    public string UcjbToAddr { get; set; }

    public double? UcjbType { get; set; }

    public bool UcjbVoid { get; set; }

    public bool UcjbVan { get; set; }

    public string UcjbClientRefa { get; set; }

    public string UcjbClientRefb { get; set; }

    public decimal? UcjbAmount { get; set; }

    public string UcjbOurRef { get; set; }

    public string SigNotRequired { get; set; }

    public int? LeaveNotHomeId { get; set; }

    public string ClientNotes { get; set; }

    public string InternalNotes { get; set; }

    public string JobNotes { get; set; }

    public decimal? PickUpLatitude { get; set; }

    public decimal? PickUpLongitude { get; set; }

    public decimal? DeliveryLatitude { get; set; }

    public decimal? DeliveryLongitude { get; set; }

    public int? DeliverToPrivateBusiness { get; set; }

    public bool UcjbReturn { get; set; }

    public DateTime? UcjbDispDate { get; set; }

    public int? UcjbSize { get; set; }

    public int? UcjbStatus { get; set; }

    public DateTime UcjbDate { get; set; }

    public string UcclCode { get; set; }

    public string UcjbToSpecial { get; set; }

    public string UcjsCode { get; set; }

    public bool SaturdayDelivery { get; set; }

    public bool? EmailForJobFu { get; set; }

    public string FromSuburbName { get; set; }

    public string ToSuburbName { get; set; }

    public string ClientName { get; set; }

    public string ClientCode { get; set; }

    public string PickupRemain { get; set; }

    public string Remain { get; set; }

    public int? RemainTime { get; set; }

    public bool RemoteJob { get; set; }

    public string SpeedShortName { get; set; }

    public int? Minutes { get; set; }

    public int? PickupTime { get; set; }

    public int? DeliveryTime { get; set; }

    public int AlertLatePickUp { get; set; }

    public int AlertLateDelivery { get; set; }

    public string OriginalSpeed { get; set; }

    public string UcjbPodname { get; set; }

    public string NotifiedSpeed { get; set; }

    public bool Direct { get; set; }

    public bool FirstJob { get; set; }

    public int? NotifiedJobTypeId { get; set; }

    public int? AcceptedJobTypeId { get; set; }

    public int IsParentJob { get; set; }

    public int? RootParentId { get; set; }

    public int DisplaySplitJobDetail { get; set; }

    public int DisplayReturnJobDetail { get; set; }

    public int DisplayMultiJobDetail { get; set; }

    public int IsChildJob { get; set; }

    public bool? AllowSplit { get; set; }

    public string ChildNotes { get; set; }

    public bool? AllowDespatch { get; set; }

    public string ClosestCourierId { get; set; }

    public int? JobRelationshipTypeId { get; set; }

    public int? UcclAccountStatus { get; set; }

    public int? Cdt { get; set; }

    public byte PickRunOrder { get; set; }

    public byte DropRunOrder { get; set; }

    public bool UcjbMobileSend { get; set; }

    public bool? SendJobsViaSms { get; set; }

    public string UcjbFromAddr { get; set; }

    public bool? Truck { get; set; }

    public int? InternalStatus { get; set; }

    public DateTime? FollowupTime { get; set; }

    public bool? Reprice { get; set; }

    public int? SiteId { get; set; }

    public int? ToSiteId { get; set; }

    public decimal? PickupAmount { get; set; }

    public decimal? DropoffAmount { get; set; }

    public bool? BulletFreight { get; set; }

    public bool? VanOk { get; set; }

    public int? Dgclass { get; set; }

    public bool InternalAccount { get; set; }

    public int? FromArea { get; set; }

    public int? ToArea { get; set; }

    public int? FromSuburbId { get; set; }

    public int? ToSuburbId { get; set; }

    public bool DesCheck { get; set; }

    public int? FdcourierId { get; set; }

    public string FdcourierCode { get; set; }

    public int HasGeoLocation { get; set; }

    public int? TruckWeightLimit { get; set; }

    public DateTime? TruckStartTime { get; set; }

    public double? TruckHours { get; set; }

    public string DeliverToContact { get; set; }

    public byte[] DeliveryPhoto { get; set; }

    public string DeliverToPhone { get; set; }

    public int? TrackingMethod { get; set; }

    public string TrackingMobile { get; set; }

    public string TrackingEmail { get; set; }

    public string Udstatus { get; set; }

    public bool? Dgdocument { get; set; }

    public bool RatedManually { get; set; }

    public bool UcjbCbd { get; set; }

    public bool? UcjbLocked { get; set; }

    public decimal? Gstrate { get; set; }

    public string ScheduleName { get; set; }

    public string FromPostCode { get; set; }

    public string ToPostCode { get; set; }

    public string SpeedName { get; set; }

    public string NotifiedName { get; set; }

    public string OriginalName { get; set; }

    public string LoggedInContactName { get; set; }

    public string StatusName { get; set; }

    public string StatusCode { get; set; }

    public string ToCity { get; set; }

    public string ClientItemIds { get; set; }

    public bool? DisplayDespatch { get; set; }

    public bool? DisplayInDespatch { get; set; }

    public string AcceptedName { get; set; }

    public string PickupAddressLine1 { get; set; }

    public string PickupAddressLine2 { get; set; }

    public string PickupAddressLine3 { get; set; }

    public string PickupAddressLine4 { get; set; }

    public string PickupAddressLine5 { get; set; }

    public string PickupAddressLine6 { get; set; }

    public string PickupAddressLine7 { get; set; }

    public string PickupAddressLine8 { get; set; }

    public string DeliveryAddressLine1 { get; set; }

    public string DeliveryAddressLine2 { get; set; }

    public string DeliveryAddressLine3 { get; set; }

    public string DeliveryAddressLine4 { get; set; }

    public string DeliveryAddressLine5 { get; set; }

    public string DeliveryAddressLine6 { get; set; }

    public string DeliveryAddressLine7 { get; set; }

    public string DeliveryAddressLine8 { get; set; }

    public int? ToAirportId { get; set; }

    public int? FromAirportId { get; set; }

    public int? HasNationwide { get; set; }

    public DateTime? ExpectedArrival { get; set; }

    public DateTime? ExpectedDeparture { get; set; }

    public string FlightNumber { get; set; }

    public string FlightNotes { get; set; }

    public int? AgentId { get; set; }

    public string AgentName { get; set; }

    public string AgentRankingName { get; set; }

    public int? BulkRegionId { get; set; }

    public int? ClearListAreaId { get; set; }
}