// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class DfrntappUserViewPermission
{
    public int UserViewPermissionId { get; set; }

    public int? UserId { get; set; }

    public int? ViewId { get; set; }

    public bool? IsVisible { get; set; }

    public int? SortOrder { get; set; }

    public virtual TucStaff User { get; set; }

    public virtual TblDespatchView View { get; set; }
}