// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class Dfrntapp
{
    public int AppId { get; set; }

    public string AppName { get; set; }

    public string CreatedBy { get; set; }

    public DateTime Created { get; set; }

    public virtual ICollection<DfrntappPage> DfrntappPages { get; set; } = new List<DfrntappPage>();
}