// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class ExtraCharge
{
    public int ExtraChargeId { get; set; }

    public string ExtraChargeName { get; set; }

    public decimal? WeightIncluded { get; set; }

    public decimal? WeightExcess { get; set; }

    public decimal? WeightExcessDp { get; set; }

    public bool? ApplyWeightFuel { get; set; }

    public int? WaitTimeIncluded { get; set; }

    public int? WaitTimePeriod { get; set; }

    public decimal? WaitTimeExcess { get; set; }

    public decimal? WaitTimeExcessDp { get; set; }

    public bool? ApplyWaitTimeFuel { get; set; }

    public decimal? ExtraStop { get; set; }

    public decimal? ExtraStopDp { get; set; }

    public bool? ApplyExtraStopFuel { get; set; }

    public decimal? AfterHours { get; set; }

    public decimal? AfterHoursDp { get; set; }

    public bool? ApplyAfterHoursFuel { get; set; }

    public decimal? HolidayCharge { get; set; }

    public decimal? HolidayChargeDp { get; set; }

    public bool? ApplyHolidayFuel { get; set; }

    public decimal? PalletExcess { get; set; }

    public decimal? PalletExcessDp { get; set; }

    public decimal? PalletsIncluded { get; set; }

    public bool? ApplyPalletsFuel { get; set; }

    public decimal? DryIceCharge { get; set; }

    public decimal? DryIceChargeDp { get; set; }

    public bool? ApplyDryIceFuel { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public int? WaitTimeInterval { get; set; }

    public decimal? DangerousGoodsCharge { get; set; }

    public decimal? DangerousGoodsChargeDp { get; set; }

    public bool? ApplyDangerousGoodsFuel { get; set; }

    public int? ClientId { get; set; }

    public decimal? PickupHoldCharge { get; set; }

    public decimal? CubicIncluded { get; set; }

    public decimal? CubicIncrement { get; set; }

    public decimal? CubicExcess { get; set; }

    public decimal? CubicExcessDp { get; set; }

    public bool? ApplyCubicFuel { get; set; }

    public int? ItemsIncluded { get; set; }

    public decimal? ItemsExcess { get; set; }

    public decimal? ItemsExcessDp { get; set; }

    public bool? ApplyItemFuel { get; set; }

    public bool? Active { get; set; }

    public int? RateCardId { get; set; }

    public decimal? ExtraItemMultiplier { get; set; }

    public decimal? WeightIncrement { get; set; }

    public virtual ICollection<AirFreightRate> AirFreightRates { get; set; } = new List<AirFreightRate>();
}