// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class Feature
{
    public string FeatureKey { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public string ParentKey { get; set; }

    public int? Tier { get; set; }

    public int? SortOrder { get; set; }

    public string AvailableCountries { get; set; }

    public bool ClientVisible { get; set; }

    public string ReleaseStatus { get; set; }

    public virtual ICollection<ClientTypeFeature> ClientTypeFeatures { get; set; } = new List<ClientTypeFeature>();

    public virtual ICollection<Feature> InverseParentKeyNavigation { get; set; } = new List<Feature>();

    public virtual Feature ParentKeyNavigation { get; set; }
}