// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class FlightZoneCombo
{
    public int FlightZoneComboId { get; set; }

    public string FromZoneName { get; set; }

    public string ToZoneName { get; set; }

    public int? CarrierId { get; set; }

    public int AirFreightRateId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual AirFreightRate AirFreightRate { get; set; }

    public virtual FlightCarrier Carrier { get; set; }
}