// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class FlightCarrier
{
    public int FlightCarrierId { get; set; }

    public string FlightCarrierName { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public bool IsActive { get; set; }

    public string CarrierCode { get; set; }

    public virtual ICollection<FlightCarrierZone> FlightCarrierZones { get; set; } = new List<FlightCarrierZone>();

    public virtual ICollection<FlightZoneCombo> FlightZoneCombos { get; set; } = new List<FlightZoneCombo>();
}