// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class GlobalAddressMapping
{
    public int GlobalAddressId { get; set; }

    public int AddressLineNo { get; set; }

    public string AddressComponent { get; set; }

    public string Country { get; set; }

    public int? ClientId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }
}