// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DespatchWeb.EntityClasses;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DespatchWeb.EntityClasses
{
    public partial interface IDespatchContextProcedures
    {
        Task<List<DD_stpGetAgentDistanceRateResult>> DD_stpGetAgentDistanceRateAsync(int? ClientID, int? FromZipCode, int? ToZipCode, decimal? TotalMiles, decimal? TotalWeight, int? TotalPallets, int? ExtraStopOffs, DateTime? BookTime, int? VehicleSizeID, bool? DangerousGoods, decimal? DryIceWeight, int? WaitTime, int? DistanceRateID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_qdfCourier_ClearListsResult>> DES_qdfCourier_ClearListsAsync(int? ClearListAreaID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DES_qdfEvent_InsertAsync(string JobNo, int? ClientID, string Contact, DateTime? Date, DateTime? Time, double? Type, double? LateTime, DateTime? ETATime, double? StaffIDIn, double? StaffIDOut, DateTime? ResponseTime, string Notes, bool? PageCourier, bool? Closed, int? Originator, string Description, int? CourierID, int? JobID, string Despatcher, int? JobType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_qdfCourier_ClearListsResult>> DES_qdfUS_Courier_ClearListsAsync(int? ClearListAreaID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_qryCourierCombo_ActiveResult>> DES_qryCourierCombo_ActiveAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_qryTruckCourierStatusResult>> DES_qryTruckCourierStatusAsync(string CourierID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_stpJob_ColsolidateMarsInformationResult>> DES_stpJob_ColsolidateMarsInformationAsync(int? JobID, bool? Consolidate, string UserName, int? DespatchChangesID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DES_stpJob_DisplayInDespatchAsync(int? JobID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_stpJob_SplitJobResult>> DES_stpJob_SplitJobAsync(int? JobID, bool? PreBookJob, string UserName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DES_stpJobBooking_AddNotesAsync(int? JobID, string Notes, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_stpJobBooking_InsertJobAndChildrenResult>> DES_stpJobBooking_InsertJobAndChildrenAsync(int? JobBookingID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DES_stpSettingsResult>> DES_stpSettingsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DESWEB_qryClientsActiveResult>> DESWEB_qryClientsActiveAsync(string SearchTerm, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DESWEB_qryCourierActiveResult>> DESWEB_qryCourierActiveAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DESWeb_qryCourierComboResult>> DESWeb_qryCourierComboAsync(string SearchTerm, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DESWEB_qryPotentialCouriersResult>> DESWEB_qryPotentialCouriersAsync(int? JobID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpBulkJob_AddNotesAsync(int? BulkJobID, string Notes, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpJob_AddNotesAsync(int? JobID, string Notes, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpJobItems_DeleteAsync(int? JobID, int? ItemID, bool? Prebook, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpJobItems_InsertAsync(int? JobID, int? Items, double? Weight, double? Length, double? Height, double? Depth, bool? PU, bool? DO, int? DGClass, string Notes, bool? Prebook, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpJobItems_UpdateAsync(int? JobID, int? ItemID, int? Items, double? Weight, double? Length, double? Height, double? Depth, bool? PU, bool? DO, int? DGClass, string Notes, bool? Prebook, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DESWEB_stpMapEnvelopeResult>> DESWEB_stpMapEnvelopeAsync(decimal? MinimumLongitude, decimal? MinimumLatitude, decimal? MaximumLongitude, decimal? MaximumLatitude, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpQuickCreateJobAsync(int? ClientId, string PickupAddressLine1, string PickupAddressLine2, string PickupAddressLine3, string PickupAddressLine4, string PickupAddressLine5, string PickupAddressLine6, string PickupAddressLine7, string PickupAddressLine8, decimal? PickupLat, decimal? PickupLong, string DeliveryAddressLine1, string DeliveryAddressLine2, string DeliveryAddressLine3, string DeliveryAddressLine4, string DeliveryAddressLine5, string DeliveryAddressLine6, string DeliveryAddressLine7, string DeliveryAddressLine8, decimal? DeliveryLat, decimal? DeliveryLong, string PickupFromContact, DateTime? JobDate, bool? Void, bool? Van, bool? Attention, string DeliverToContact, string PodName, bool? Truck, bool? VanOk, bool? Reprice, decimal? Amount, int? SpeedId, int? StaffId, string RefA, string RefB, OutputParameter<int?> JobId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateBulkJobAsync(int? BulkJobID, string PropertyName, string Value, decimal? Rate, string Username, int? StaffID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateBulkJobDeliveryAddressAsync(int? BulkJobID, string ToSuburb, int? ToPostCode, string Address, decimal? DeliveryLatitude, decimal? DeliveryLongitude, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateBulkJobPickupAddressAsync(int? BulkJobID, string FromSuburb, int? FromPostCode, string Address, decimal? PickupLatitude, decimal? PickupLongitude, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateJobAsync(int? JobID, string PropertyName, string Value, decimal? Rate, string Username, int? StaffID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateJobBookingAsync(int? JobID, string PropertyName, string Value, decimal? Rate, string Username, int? StaffID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateJobBookingDeliveryAddressAsync(int? JobID, int? ToSuburb, string Address, decimal? DeliveryLatitude, decimal? DeliveryLongitude, bool? CBD, decimal? Rate, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateJobBookingPickupAddressAsync(int? JobID, int? FromSuburb, string Address, decimal? PickupLatitude, decimal? PickupLongitude, bool? CBD, decimal? Rate, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateJobTypeAsync(int? JobID, int? JobType, string Username, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpUpdateSplitJobMeetingAddressAsync(int? JobID, int? Suburb, string Address, decimal? DeliveryLatitude, decimal? DeliveryLongitude, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DESWEB_stpVoidPrebookJobAsync(int? JobBookingID, string Username, int? StaffID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<INT_stpIsValidLogin_DespatchResult>> INT_stpIsValidLogin_DespatchAsync(string WindowsLogonUserName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<MAP_stpClearListArea_EnvelopeResult>> MAP_stpClearListArea_EnvelopeAsync(int? ClearListAreaID, bool? IncludeCouriers, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<MAP_stpCourierGPS_LastPositionTodayResult>> MAP_stpCourierGPS_LastPositionTodayAsync(string CourierCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> NET_stpJob_Insert_JobNumberAsync(int? StaffID, int? JobTypeID, OutputParameter<string> JobNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<qry_tucJobItemsResult>> qry_tucJobItemsAsync(int? JobID, int? TruckWeightLimit, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_RateJob2Async(int? intClientID, int? intFromID, int? intToID, int? intSpeed, bool? bolPedal, bool? bolVan, bool? bolReturn, int? intWeight, int? Size, bool? IncludeFuelSurcharge, string OurRef, string ClientRefA, string ClientRefB, int? Quantity, DateTime? Booked, OutputParameter<decimal?> curAmount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<UTL_stpJob_tblBulkJob_ReleaseByJobNumberResult>> UTL_stpJob_tblBulkJob_ReleaseByJobNumberAsync(string JobNumber, DateTime? DateTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UTL_stpPPD_ExclusiveAmountAsync(int? ClientID, decimal? Amount, OutputParameter<decimal?> PPD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
