// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class IntMgrPartnerPairing
{
    public int Id { get; set; }

    public int CarrierIntegrationId { get; set; }

    public string PartnerTenantId { get; set; }

    public string PartnerTenantName { get; set; }

    public string PartnerBaseUrl { get; set; }

    public string InvitationToken { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }
}