// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class JobAccessorialCharge
{
    public int JobAccessorialChargeId { get; set; }

    public int JobId { get; set; }

    public int AccessorialChargeId { get; set; }

    public decimal? InputValue { get; set; }

    public int ItemCount { get; set; }

    public decimal? CalculatedAmount { get; set; }

    public decimal? OverrideAmount { get; set; }

    public string Notes { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string AddedAtStage { get; set; }

    public virtual AccessorialCharge AccessorialCharge { get; set; }

    public virtual TucJob Job { get; set; }
}