// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class JobPartnerDispatch
{
    public int JobId { get; set; }

    public int PartnerPairingId { get; set; }

    public virtual TucJob Job { get; set; }

    public virtual IntMgrPartnerPairing PartnerPairing { get; set; }
}