// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class JobRecoveryAgent
{
    public int RecoveryId { get; set; }

    public int JobId { get; set; }

    public int AgentId { get; set; }

    public int AirportId { get; set; }

    public int CreatedBy { get; set; }

    public int UpdatedBy { get; set; }

    public bool IsPrimary { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime UpdatedOn { get; set; }

    public virtual TucAgent Agent { get; set; }

    public virtual TblAirport Airport { get; set; }

    public virtual TucStaff CreatedByNavigation { get; set; }

    public virtual TucJob Job { get; set; }

    public virtual TucStaff UpdatedByNavigation { get; set; }
}