// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class MAP_stpCourierGPS_LastPositionTodayResult
    {
        [Column("Longitude", TypeName = "decimal(18,9)")]
        public decimal? Longitude { get; set; }
        [Column("Latitude", TypeName = "decimal(18,9)")]
        public decimal? Latitude { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
        public int? JobID { get; set; }
        public bool GPSWasEstimated { get; set; }
        public string rawdata { get; set; }
        public string CourierName { get; set; }
        public string FirstName { get; set; }
    }
}
