// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class MAP_stpClearListArea_EnvelopeResult
    {
        [Column("MinimumLongitude", TypeName = "decimal(19,9)")]
        public decimal? MinimumLongitude { get; set; }
        [Column("MinimumLatitude", TypeName = "decimal(19,9)")]
        public decimal? MinimumLatitude { get; set; }
        [Column("MaximumLongitude", TypeName = "decimal(19,9)")]
        public decimal? MaximumLongitude { get; set; }
        [Column("MaximumLatitude", TypeName = "decimal(19,9)")]
        public decimal? MaximumLatitude { get; set; }
    }
}
