// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class PricingBreakdownAllocation
{
    public int PricingBreakdownAllocationId { get; set; }

    public int ParentPricingBreakdownId { get; set; }

    public int LegJobId { get; set; }

    public decimal SharePercent { get; set; }

    public decimal ChargeAmount { get; set; }

    public decimal? CostAmount { get; set; }

    public decimal? CostOverride { get; set; }

    public bool IsAccessorial { get; set; }

    public virtual TucJob LegJob { get; set; }

    public virtual PricingBreakdown ParentPricingBreakdown { get; set; }
}