// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class qry_tucJobItemsResult
    {
        public int intQuantity { get; set; }
        public double intWeight { get; set; }
        public double totalWeight { get; set; }
        public int intPU { get; set; }
        public int intDO { get; set; }
        public double intOversizeItems { get; set; }
        public int intOverWeightItems { get; set; }
        public int DGClass { get; set; }
    }
}
