// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class REP_qryPerformance_Summary_PerformanceSpendResult
    {
        [Column("Job Number")]
        [StringLength(50)]
        public string JobNumber { get; set; }
        [StringLength(15)]
        public string ucjbType { get; set; }
        public DateTime? Date { get; set; }
        public DateTime? Booked { get; set; }
        [StringLength(30)]
        public string BookedBy { get; set; }
        [Column("Picked up time")]
        public DateTime? Pickeduptime { get; set; }
        public DateTime? Delivered { get; set; }
        [Column("Total Time")]
        public int? TotalTime { get; set; }
        public int? DeliveryMins { get; set; }
        [Column("POD Name")]
        [StringLength(100)]
        public string PODName { get; set; }
        [StringLength(30)]
        public string Booker { get; set; }
        [Column("Achieved Speed")]
        [StringLength(50)]
        public string AchievedSpeed { get; set; }
        [StringLength(30)]
        public string From { get; set; }
        [Column("From Postcode")]
        [StringLength(200)]
        public string FromPostcode { get; set; }
        [StringLength(4000)]
        public string To { get; set; }
        [Column("To Postcode")]
        [StringLength(200)]
        public string ToPostcode { get; set; }
        [StringLength(150)]
        public string ucjbFromAddr { get; set; }
        [StringLength(150)]
        public string Address { get; set; }
        public int Courier { get; set; }
        [Column("Late Pickup")]
        public int? LatePickup { get; set; }
        [Column("Late Delivery")]
        public int? LateDelivery { get; set; }
        [StringLength(150)]
        public string ucclLegalName { get; set; }
        public int? ucjbSpeed { get; set; }
        [StringLength(4000)]
        public string Notes { get; set; }
        [Column("Charge($) Excl GST", TypeName = "money")]
        public decimal? ChargeExclGST { get; set; }
        [Column("RawBaseAmount", TypeName = "money")]
        public decimal? RawBaseAmount { get; set; }
        [Column("FuelSurchargeAmount", TypeName = "money")]
        public decimal FuelSurchargeAmount { get; set; }
        [Column("Ref A")]
        [StringLength(20)]
        public string RefA { get; set; }
        [Column("Ref B")]
        [StringLength(15)]
        public string RefB { get; set; }
        [Column("Urgent Ref")]
        [StringLength(20)]
        public string UrgentRef { get; set; }
        public double? Weight { get; set; }
        [StringLength(5)]
        public string Vehicle { get; set; }
        public short? Quantity { get; set; }
        public int? ucjbYear { get; set; }
        public int? ucjbMonth { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(50)]
        public string uccrName { get; set; }
        public int? ucjbInvoiceNo { get; set; }
        public int? ucjbLocked { get; set; }
        public int? ucjbClientID { get; set; }
        public string ucclNote { get; set; }
        public int? Minutes { get; set; }
    }
}
