// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class Route
{
    public int RouteId { get; set; }

    public string Name { get; set; }

    public string Area { get; set; }

    public int? DefaultCourierId { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public byte? DefaultTargetType { get; set; }

    public int? DefaultAgentId { get; set; }

    public int? ScheduleId { get; set; }

    public virtual TucAgent DefaultAgent { get; set; }

    public virtual TucCourier DefaultCourier { get; set; }

    public virtual ICollection<TucJob> TucJobs { get; set; } = new List<TucJob>();
}