// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class StaffDispatchLayout
{
    public Guid Id { get; set; }

    public int StaffId { get; set; }

    public string Page { get; set; }

    public string Name { get; set; }

    public string LayoutJson { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedUtc { get; set; }

    public DateTime LastModifiedUtc { get; set; }

    public virtual TucStaff Staff { get; set; }
}