// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblAppWidget
{
    public int AppWidgetId { get; set; }

    public int AppId { get; set; }

    public int WidgetId { get; set; }

    public bool IsRequired { get; set; }

    public int DefaultOrder { get; set; }

    public virtual TblDfrntapp App { get; set; }

    public virtual ICollection<UserWidgetPreference> UserWidgetPreferences { get; set; } = new List<UserWidgetPreference>();

    public virtual TblWidget Widget { get; set; }
}