// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblBulkEvent
{
    public int BulkEventId { get; set; }

    public int? BulkJobId { get; set; }

    public int? CourierId { get; set; }

    public string Notes { get; set; }

    public bool Internal { get; set; }

    public bool ClientFollowup { get; set; }

    public bool ClientCreated { get; set; }

    public string CreatedByName { get; set; }

    public DateTime EventDate { get; set; }

    public DateTime Created { get; set; }

    public DateTime? ClosedDate { get; set; }

    public string ClosedByName { get; set; }

    public virtual TblBulkJob BulkJob { get; set; }

    public virtual TucCourier Courier { get; set; }
}