// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblBulkScan
{
    public int BulkScanId { get; set; }

    public DateTime ScanDateTime { get; set; }

    public string Scan { get; set; }

    public int ScanType { get; set; }

    public int? CourierId { get; set; }

    public int? ToCourierId { get; set; }

    public string RunName { get; set; }

    public virtual TucCourier ToCourier { get; set; }
}