// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblClearListAreaOrder
{
    public int ClearListAreaOrderId { get; set; }

    public int CourierId { get; set; }

    public int ClearListAreaId { get; set; }

    public DateTime OrderTime { get; set; }

    public int Status { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public virtual TblClearListArea ClearListArea { get; set; }

    public virtual TucCourier Courier { get; set; }
}