// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblClearListArea
{
    public int ClearListAreaId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int ChannelId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public int Order { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<TblClearListAreaPolygon> TblClearListAreaPolygons { get; set; } = new List<TblClearListAreaPolygon>();

    public virtual ICollection<ZoneGroup> ZoneGroups { get; set; } = new List<ZoneGroup>();
}