// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
    public partial class TblClientContactJobType
    {
        public int ClientContactJobTypeId { get; set; }
        public int ClientContactId { get; set; }
        public int JobTypeId { get; set; }
        public int PickupTime { get; set; }
        public string PickupType { get; set; }
        public int DeliveryTime { get; set; }
        public string DeliveryType { get; set; }
        public string CreatedBy { get; set; }
        public DateTime Created { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime LastModified { get; set; }
        public string Notes { get; set; }

        public virtual TblClientContact ClientContact { get; set; }
        public virtual TucClientContact ClientContactNavigation { get; set; }
        public virtual TucJobType JobType { get; set; }
    }
}