// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblClientAvailableSpeedItem
{
    public int Id { get; set; }

    public int ClientAvailableSpeedId { get; set; }

    public int ClientItemId { get; set; }

    public bool Active { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual TblClientAvailableSpeed ClientAvailableSpeed { get; set; }

    public virtual TucClientItem ClientItem { get; set; }
}