// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblCourierGp
{
    public int CourierGpsid { get; set; }

    public int CourierId { get; set; }

    public string RawData { get; set; }

    public int? PolygonId { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Latitude { get; set; }

    public DateTime Created { get; set; }

    public int? JobId { get; set; }

    public string Action { get; set; }

    public bool GpswasEstimated { get; set; }

    public virtual TblPolygon Polygon { get; set; }

    public virtual ICollection<TucCourier> TucCouriers { get; set; } = new List<TucCourier>();
}