// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblClientContactInternetPermission
{
    public int ClientContactId { get; set; }

    public int InternetPermissionId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public virtual TblClientContact ClientContact { get; set; }

    public virtual TblInternetPermission InternetPermission { get; set; }
}