// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblDfrntapp
{
    public int AppId { get; set; }

    public string AppName { get; set; }

    public int CreatedBy { get; set; }

    public DateTime Created { get; set; }

    public virtual ICollection<TblAppWidget> TblAppWidgets { get; set; } = new List<TblAppWidget>();
}