// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblEcoSetting
{
    public int SettingId { get; set; }

    public bool? EconomyZones { get; set; }

    public bool? EconomyRuns { get; set; }

    public DateTime? EconomyDeliveryTime { get; set; }

    public DateTime? EconomyRun1 { get; set; }

    public DateTime? EconomyRun2 { get; set; }

    public DateTime? EconomyRun3 { get; set; }

    public DateTime? EconomyRun4 { get; set; }

    public DateTime? EconomyRun5 { get; set; }

    public DateTime? EconomyCutOff { get; set; }

    public DateTime? EconomyRebook { get; set; }

    public DateTime? BaggageCutOff { get; set; }

    public DateTime? BaggageRebook { get; set; }
}