// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblHoliday
{
    public int HolidayId { get; set; }

    public string Name { get; set; }

    public int SiteId { get; set; }

    public string JobEntryType { get; set; }

    public DateTime Date { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int? CourierId { get; set; }

    public decimal Amount { get; set; }

    public bool CanBook { get; set; }

    public string Message { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public int? ClientId { get; set; }

    public int? SpeedId { get; set; }

    public bool AllSpeeds { get; set; }

    public virtual TucCourier Courier { get; set; }
}