// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblPolygon
{
    public int PolygonId { get; set; }

    public string Name { get; set; }

    public int ExternalId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public int? AreaId { get; set; }

    public virtual ICollection<TblClearListAreaPolygon> TblClearListAreaPolygons { get; set; } = new List<TblClearListAreaPolygon>();

    public virtual ICollection<TblCourierGp> TblCourierGps { get; set; } = new List<TblCourierGp>();

    public virtual ICollection<TblPolygonGp> TblPolygonGps { get; set; } = new List<TblPolygonGp>();

    public virtual ICollection<TblPolygonSuburb> TblPolygonSuburbs { get; set; } = new List<TblPolygonSuburb>();
}