// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblPolygonGp
{
    public int PolygonGpsid { get; set; }

    public int PolygonId { get; set; }

    public decimal Longitude { get; set; }

    public decimal Latitude { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public virtual TblPolygon Polygon { get; set; }

    public virtual TucSuburb PolygonNavigation { get; set; }
}