// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblPolygonSuburb
{
    public int PolygonSuburbId { get; set; }

    public int PolygonId { get; set; }

    public int SuburbId { get; set; }

    public virtual TblPolygon Polygon { get; set; }

    public virtual TucSuburb Suburb { get; set; }
}