// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TblSmppsetting
{
    public int SettingId { get; set; }

    public string Smscaddress { get; set; }

    public string Smscusername { get; set; }

    public string Smscpassword { get; set; }

    public string Smscaddress2 { get; set; }

    public string Smscusername2 { get; set; }

    public string Smscpassword2 { get; set; }

    public int IntervalSeconds { get; set; }

    public int WaitIntervalMilliseconds { get; set; }

    public short CountryCode { get; set; }

    public string SourcePrefix { get; set; }

    public string MessageFormat { get; set; }

    public int MessageLength { get; set; }

    public byte LogFileLevel { get; set; }

    public int ListBoxLimit { get; set; }

    public string ErrorEmail { get; set; }

    public string MessageEmail { get; set; }

    public bool Development { get; set; }

    public short Npi { get; set; }

    public short Ton { get; set; }

    public short? Npi2 { get; set; }

    public short? Ton2 { get; set; }

    public bool ProcessMsg { get; set; }

    public string PodemailMessage { get; set; }

    public string PodemailSubject { get; set; }

    public string Podsmsmessage { get; set; }

    public string PodemailReplyAddress { get; set; }

    public string PodemailReplyAddressName { get; set; }

    public string JobUpdateLatePickupEmailMessage { get; set; }

    public string JobUpdateLatePickupEmailUpdateMessage { get; set; }

    public string JobUpdateLatePickupEmailSubject { get; set; }

    public string JobUpdateLatePickupSmsmessage { get; set; }

    public string JobUpdateLatePickupSmsupdateMessage { get; set; }

    public string JobUpdateLateDeliveryEmailMessage { get; set; }

    public string JobUpdateLateDeliveryEmailUpdateMessage { get; set; }

    public string JobUpdateLateDeliveryEmailSubject { get; set; }

    public string JobUpdateLateDeliverySmsmessage { get; set; }

    public string JobUpdateLateDeliverySmsupdateMessage { get; set; }

    public string JobUpdateEmailReplyAddress { get; set; }

    public string JobUpdateEmailReplyAddressName { get; set; }

    public string BusySpeedoEmailAddress { get; set; }

    public string BusySpeedoEmailSubject { get; set; }

    public string BusySpeedoEmailMessage { get; set; }

    public int BusySpeedoIntervalSeconds { get; set; }

    public string ContactValidateEmailMessage { get; set; }

    public string ContactValidateEmailSubject { get; set; }

    public string ContactValidateEmailReminderMessage { get; set; }

    public string ContactValidateEmailReminderSubject { get; set; }

    public string ContactValidateEmailValidatedMessage { get; set; }

    public string ContactValidateEmailValidatedSubject { get; set; }

    public string ContactForgotPasswordResetPasswordMessage { get; set; }

    public string ContactForgotPasswordResetPasswordSubject { get; set; }

    public string ContactAdhocMessage { get; set; }

    public string ContactAdhocSubject { get; set; }

    public bool SendContactAdhocEmails { get; set; }

    public string JobUpdateLateDeliveryEmailDirectMessage { get; set; }

    public string JobUpdateLateDeliveryEmailDirectUpdateMessage { get; set; }

    public string JobUpdateLateDeliveryEmailAsapmessage { get; set; }

    public string JobUpdateLateDeliveryEmailAsapupdateMessage { get; set; }

    public string JobUpdateLateDeliverySmsdirectMessage { get; set; }

    public string JobUpdateLateDeliverySmsdirectUpdateMessage { get; set; }

    public string JobUpdateLateDeliverySmsasapmessage { get; set; }

    public string JobUpdateLateDeliverySmsasapupdateMessage { get; set; }

    public string JobUpdateLateDeliveryEmaiDirectSubject { get; set; }

    public string JobUpdateLateDeliveryEmailAsapsubject { get; set; }

    public string JobUpdateSpeedChangeEmailMessage { get; set; }

    public string JobUpdateSpeedChangeEmailSubject { get; set; }

    public string JobUpdateSpeedChangeSmsmessage { get; set; }

    public string JobItemNotReadyEmailSubject { get; set; }

    public string JobItemNotReadyEmailMessage { get; set; }

    public string JobTrackingEmailMessage { get; set; }

    public string JobTrackingEmailSubject { get; set; }

    public string JobTrackingSmsmessage { get; set; }

    public string JobTrackingEmailReplyAddress { get; set; }

    public string JobTrackingEmailReplyAddressName { get; set; }

    public string AgentEmailSubject { get; set; }

    public string AgentEmailMessage { get; set; }

    public string AgentSmsmessage { get; set; }

    public string AgentEmailReplyAddress { get; set; }

    public string AgentEmailReplyAddressName { get; set; }

    public string AgentFilePath { get; set; }
}