// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TimeZone
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Code { get; set; }

    public int OffsetHours { get; set; }

    public string OffsetString { get; set; }

    public virtual ICollection<TblBulkJob> TblBulkJobs { get; set; } = new List<TblBulkJob>();

    public virtual ICollection<TucJobArchive> TucJobArchiveDeliverByTimeZones { get; set; } = new List<TucJobArchive>();

    public virtual ICollection<TucJobArchive> TucJobArchivePickupTimeZones { get; set; } = new List<TucJobArchive>();

    public virtual ICollection<TucJobBooking> TucJobBookingDeliverByTimeZones { get; set; } = new List<TucJobBooking>();

    public virtual ICollection<TucJobBooking> TucJobBookingPickupTimeZones { get; set; } = new List<TucJobBooking>();

    public virtual ICollection<TucJob> TucJobDeliverByTimeZones { get; set; } = new List<TucJob>();

    public virtual ICollection<TucJob> TucJobPickupTimeZones { get; set; } = new List<TucJob>();
}