// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucAgent
{
    public int UcagId { get; set; }

    public string UcagName { get; set; }

    public string UcagAddress { get; set; }

    public int UcagSuburbId { get; set; }

    public string UcagPhone { get; set; }

    public string UcagFax { get; set; }

    public string UcagAltPhone { get; set; }

    public string UcagAltFax { get; set; }

    public string UcagNotes { get; set; }

    public int? NumRef1 { get; set; }

    public int? NumRef2 { get; set; }

    public int? NumRef3 { get; set; }

    public string TextRef1 { get; set; }

    public string TextRef2 { get; set; }

    public string TextRef3 { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public decimal? Flagfall { get; set; }

    public decimal? KilometerRate { get; set; }

    public decimal? ItemRate { get; set; }

    public string PostCode { get; set; }

    public int? SiteId { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public int? MaxKms { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string AddressLine4 { get; set; }

    public string AddressLine5 { get; set; }

    public string AddressLine6 { get; set; }

    public string AddressLine7 { get; set; }

    public string AddressLine8 { get; set; }

    public decimal? AgentRateMarkup { get; set; }

    public int? RankingId { get; set; }

    public int? StatusId { get; set; }

    public bool IsNetworkPartner { get; set; }

    public bool NpPortalEnabled { get; set; }

    public byte NpTier { get; set; }

    public string Association { get; set; }

    public string AssociationMemberId { get; set; }

    public string ContactName { get; set; }

    public string ContactEmail { get; set; }

    public decimal? DefaultCourierPayPercent { get; set; }

    public bool OptedInToBcti { get; set; }

    public int? BctiScheduleId { get; set; }

    public string AccountsId { get; set; }

    public virtual ICollection<AgentVehicle> AgentVehicles { get; set; } = new List<AgentVehicle>();

    public virtual ICollection<IntMgrPartnerPairing> IntMgrPartnerPairings { get; set; } = new List<IntMgrPartnerPairing>();

    public virtual ICollection<JobDeliveryJourney> JobDeliveryJourneyNewAgents { get; set; } = new List<JobDeliveryJourney>();

    public virtual ICollection<JobDeliveryJourney> JobDeliveryJourneyOldAgents { get; set; } = new List<JobDeliveryJourney>();

    public virtual ICollection<JobRecoveryAgent> JobRecoveryAgents { get; set; } = new List<JobRecoveryAgent>();

    public virtual TucAgentRanking Ranking { get; set; }

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();

    public virtual ICollection<TblAfterHour> TblAfterHours { get; set; } = new List<TblAfterHour>();

    public virtual ICollection<TblAirport> TblAirports { get; set; } = new List<TblAirport>();

    public virtual ICollection<TucClient> TucClients { get; set; } = new List<TucClient>();

    public virtual ICollection<TucCourier> TucCouriers { get; set; } = new List<TucCourier>();

    public virtual ICollection<TucJobArchive> TucJobArchives { get; set; } = new List<TucJobArchive>();

    public virtual ICollection<TucJob> TucJobs { get; set; } = new List<TucJob>();

    public virtual TucSuburb UcagSuburb { get; set; }
}