// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

    public partial class TucContact
    {
    public int UccoId { get; set; }

        public int UccoId { get; set; }
        public string UccoName { get; set; }

        public int? UccoClientId { get; set; }

    public virtual ICollection<TucJobBooking> TucJobBookings { get; set; } = new List<TucJobBooking>();

        public virtual TucClient UccoClient { get; set; }
        public virtual ICollection<TucJobBooking> TucJobBookings { get; set; }
    }
}