// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucClientItem
{
    public int ItemId { get; set; }

    public int ClientId { get; set; }

    public string Name { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Description { get; set; }

    public bool PerItem { get; set; }

    public decimal Rate { get; set; }

    public int? VehicleSizeId { get; set; }

    public virtual TucClient Client { get; set; }

    public virtual ICollection<TblClientAvailableSpeedItem> TblClientAvailableSpeedItems { get; set; } = new List<TblClientAvailableSpeedItem>();

    public virtual VehicleSize VehicleSize { get; set; }
}