// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucEventTypeEventTypeGroup
{
    public int Id { get; set; }

    public int EventTypeId { get; set; }

    public int EventTypeGroupId { get; set; }

    public int Sequence { get; set; }

    public int? DueTime { get; set; }

    public bool IsActive { get; set; }

    public virtual TucEventType EventType { get; set; }

    public virtual TucEventTypeGroup EventTypeGroup { get; set; }
}