// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucEvent
{
    public int UcevId { get; set; }

    public string UcevJobNumber { get; set; }

    public int? UcevClientId { get; set; }

    public string UcevContact { get; set; }

    public DateTime? UcevDate { get; set; }

    public DateTime? UcevTime { get; set; }

    public int? UcevType { get; set; }

    public double? UcevLateTime { get; set; }

    public DateTime? UcevEtatime { get; set; }

    public int? UcevStaffIdin { get; set; }

    public int? UcevStaffIdout { get; set; }

    public DateTime? UcevResponseTime { get; set; }

    public string UcevNotes { get; set; }

    public bool UcevPageCourier { get; set; }

    public bool UcevClosed { get; set; }

    public int? UcevOriginator { get; set; }

    public string UcevDescription { get; set; }

    public int? UcevCourierId { get; set; }

    public int? UcevJobId { get; set; }

    public string UcevDespatcher { get; set; }

    public int? UcevJobType { get; set; }

    public int? SpeedId { get; set; }

    public bool UcevIsScheduled { get; set; }

    public int? UcevTimeOffset { get; set; }

    public DateTime? UcevScheduledTime { get; set; }

    public int? UcevTemplateDetailId { get; set; }

    public string UcevPayload { get; set; }

    public bool UcevNotificationSent { get; set; }

    public DateTime? UcevNotificationSentAt { get; set; }

    public DateTime UcevDueTime { get; set; }

    public virtual TucJobType Speed { get; set; }

    public virtual TucClient UcevClient { get; set; }

    public virtual TucCourier UcevCourier { get; set; }

    public virtual TucJob UcevJob { get; set; }

    public virtual TucStaff UcevStaffIdinNavigation { get; set; }

    public virtual TucStaff UcevStaffIdoutNavigation { get; set; }

    public virtual TucEventType UcevTypeNavigation { get; set; }
}