// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucInvoiceProcess
{
    public int UcipId { get; set; }

    public DateTime UcipDateTo { get; set; }

    public int UcipInvoiceType { get; set; }

    public bool UcipDone { get; set; }

    public DateTime? UcipDateDone { get; set; }

    public bool UcipPrinted { get; set; }

    public string UcipPrintedBy { get; set; }

    public DateTime? UcipPrintedDate { get; set; }

    public bool Reschedule { get; set; }

    public DateTime? StatementsCreated { get; set; }

    public int? ExternalJournalHeaderId { get; set; }

    public DateTime? PostedOa { get; set; }

    public int? OarunReference { get; set; }

    public DateTime? PostedXero { get; set; }

    public DateTime? CompletedXero { get; set; }

    public DateTime? StatementStartedXero { get; set; }

    public DateTime? StatementCompletedXero { get; set; }

    public DateTime? CompletedStripe { get; set; }

    public string CodeBonus { get; set; }

    public string ItemCodeBonus { get; set; }

    public virtual ICollection<TucInvoiceNo> TucInvoiceNos { get; set; } = new List<TucInvoiceNo>();
}