// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucItemType
{
    public int ItemTypeId { get; set; }

    public string Name { get; set; }

    public int SortOrder { get; set; }

    public int? ClientId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual TucClient Client { get; set; }

    public virtual ICollection<TblBulkJobItemType> TblBulkJobItemTypes { get; set; } = new List<TblBulkJobItemType>();

    public virtual ICollection<TucJobBookingItemType> TucJobBookingItemTypes { get; set; } = new List<TucJobBookingItemType>();

    public virtual ICollection<TucJobItemType> TucJobItemTypes { get; set; } = new List<TucJobItemType>();

    public virtual ICollection<TucJobItemTypesArchive> TucJobItemTypesArchives { get; set; } = new List<TucJobItemTypesArchive>();
}