// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucInvoiceNo
{
    public int UcinId { get; set; }

    public DateTime UcinDate { get; set; }

    public int UcinClientId { get; set; }

    public DateTime? UcinDateGenerated { get; set; }

    public bool UcinLocked { get; set; }

    public int ProcessId { get; set; }

    public DateTime? Created { get; set; }

    public int? StatementId { get; set; }

    public int? ExternalJournalHeaderId { get; set; }

    public DateTime? PostedOa { get; set; }

    public string XeroId { get; set; }

    public decimal? DiscountTotal { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? TaxTotal { get; set; }

    public decimal? Total { get; set; }

    public decimal? Ppd { get; set; }

    public decimal? PpdTax { get; set; }

    public string XeroIdPpdCancellation { get; set; }

    public bool? PpdApplied { get; set; }

    public int? InvoiceTemplateId { get; set; }

    public DateTime? Sent { get; set; }

    public DateTime? DueDate { get; set; }

    public string PpdCode { get; set; }

    public string PpdItemCode { get; set; }

    public virtual TucClient UcinClient { get; set; }
}