// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucInsuranceCompany
{
    public int UcicId { get; set; }

    public string UcicName { get; set; }

    public string UcicAddress { get; set; }

    public string UcicPhone { get; set; }

    public string UcicFax { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<TucCourier> TucCourierUccrCarrierLiabilities { get; set; } = new List<TucCourier>();

    public virtual ICollection<TucCourier> TucCourierUccrInsurances { get; set; } = new List<TucCourier>();

    public virtual ICollection<TucCourier> TucCourierUccrPublicLiabilities { get; set; } = new List<TucCourier>();
}