// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucJobType
{
    public int UcjtId { get; set; }

    public string UcjtName { get; set; }

    public string ShortName { get; set; }

    public string UcjtDescription { get; set; }

    public decimal UcjtBaseRate { get; set; }

    public decimal UcjtUnitRate { get; set; }

    public string UcjtCode { get; set; }

    public int? Minutes { get; set; }

    public int? DeliveryMargin { get; set; }

    public string JobLetter { get; set; }

    public int? PickupTime { get; set; }

    public int? DeliveryTime { get; set; }

    public bool JobEntry { get; set; }

    public bool NationwideEntry { get; set; }

    public bool DatacomEntry { get; set; }

    public bool WebJobEntry { get; set; }

    public decimal? CourierPercentage { get; set; }

    public decimal? SuccessRate { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public string SystemName { get; set; }

    public bool WebServiceEntry { get; set; }

    public int? SplitJobDeliveryTime { get; set; }

    public bool? TruckJobEntry { get; set; }

    public string ExtraName { get; set; }

    public string Alias { get; set; }

    public bool? ZoneRated { get; set; }

    public int? ServiceTrackingId { get; set; }

    public decimal? AddonPercentage { get; set; }

    public bool? Mfv { get; set; }

    public bool? Faf { get; set; }

    public int? UcjtClientId { get; set; }

    public int GroupingId { get; set; }

    public int? LabelId { get; set; }

    public bool ShowPhotosWhenChild { get; set; }

    public virtual ICollection<AirFreightRate> AirFreightRates { get; set; } = new List<AirFreightRate>();

    public virtual TucJobTypeGrouping Grouping { get; set; }

    public virtual ICollection<TblAfterHour> TblAfterHours { get; set; } = new List<TblAfterHour>();

    public virtual ICollection<TblBulkJob> TblBulkJobs { get; set; } = new List<TblBulkJob>();

    public virtual ICollection<TblBulkRunSchedule> TblBulkRunScheduleParentSpeeds { get; set; } = new List<TblBulkRunSchedule>();

    public virtual ICollection<TblBulkRunSchedule> TblBulkRunScheduleSpeeds { get; set; } = new List<TblBulkRunSchedule>();

    public virtual ICollection<TblClientAvailableSpeed> TblClientAvailableSpeeds { get; set; } = new List<TblClientAvailableSpeed>();

    public virtual ICollection<TblClientContactJobType> TblClientContactJobTypes { get; set; } = new List<TblClientContactJobType>();

    public virtual ICollection<TblJobDefault> TblJobDefaults { get; set; } = new List<TblJobDefault>();

    public virtual ICollection<TblUndeliverableLocation> TblUndeliverableLocations { get; set; } = new List<TblUndeliverableLocation>();

    public virtual ICollection<TucEvent> TucEvents { get; set; } = new List<TucEvent>();

    public virtual ICollection<TucJob> TucJobAcceptedJobTypes { get; set; } = new List<TucJob>();

    public virtual ICollection<TucJobBooking> TucJobBookings { get; set; } = new List<TucJobBooking>();

    public virtual ICollection<TucJob> TucJobDesiredJobTypes { get; set; } = new List<TucJob>();

    public virtual ICollection<TucJob> TucJobNotifiedJobTypes { get; set; } = new List<TucJob>();

    public virtual ICollection<TucJob> TucJobUcjbSpeedNavigations { get; set; } = new List<TucJob>();
}