// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucJobInternalStatus
{
    public int Tcis { get; set; }

    public string TcisName { get; set; }

    public string DefaultSchedule { get; set; }

    public int? DefaultMinutes { get; set; }

    public int? JobStatusNotificationId { get; set; }

    public virtual ICollection<TucJob> TucJobs { get; set; } = new List<TucJob>();
}