// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucJobNationwide
{
    public int UcnwId { get; set; }

    public int? UcnwJobId { get; set; }

    public string UcnwJobNumber { get; set; }

    public int UcnwClientId { get; set; }

    public int? UcnwPickUpAgentId { get; set; }

    public int? UcnwDeliveryAgentId { get; set; }

    public bool UcnwAirportOnly { get; set; }

    public int UcnwDestinationId { get; set; }

    public string UcnwConNote { get; set; }

    public string UcnwFlightNo { get; set; }

    public DateTime? UcnwEtd { get; set; }

    public DateTime? UcnwEta { get; set; }

    public string UcnwNotes { get; set; }

    public int UcnwItb { get; set; }

    public int UcnwPickUpJobId { get; set; }

    public int UcnwDeliveryJobId { get; set; }

    public DateTime? UcnwSystemDate { get; set; }

    public int? JobBookingId { get; set; }

    public string UcnwCpsignature { get; set; }

    public string WebhookAlertId { get; set; }

    public string GateNumber { get; set; }

    public int UcnwLegNumber { get; set; }

    public string UcnwAirlineName { get; set; }

    public virtual TucJobBooking JobBooking { get; set; }

    public virtual TucJob UcnwJob { get; set; }
}