// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucJobItemsArchive
{
    public int JobId { get; set; }

    public int ItemId { get; set; }

    public int Items { get; set; }

    public double Weight { get; set; }

    public double? Length { get; set; }

    public double? Height { get; set; }

    public double? Depth { get; set; }

    public bool? Pu { get; set; }

    public bool? Do { get; set; }

    public int? Dgclass { get; set; }

    public string Notes { get; set; }

    public bool? PrivateRes { get; set; }

    public decimal? Cubic { get; set; }

    public int? ChildJobId { get; set; }

    public string Barcode { get; set; }

    public virtual TucJobArchive ChildJob { get; set; }

    public virtual ICollection<TucJobItemTypesArchive> TucJobItemTypesArchives { get; set; } = new List<TucJobItemTypesArchive>();
}