// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucJobNationwide
{
    public int UcnwId { get; set; }

    public int? UcnwJobId { get; set; }

    public string UcnwJobNumber { get; set; }

    public int UcnwClientId { get; set; }

    public int? UcnwPickUpAgentId { get; set; }

    public int? UcnwDeliveryAgentId { get; set; }

    public bool UcnwAirportOnly { get; set; }

    public int UcnwDestinationId { get; set; }

    public string UcnwConNote { get; set; }

    public string UcnwFlightNo { get; set; }

    public DateTime? UcnwEtd { get; set; }

    public DateTime? UcnwEta { get; set; }

    public string UcnwNotes { get; set; }

    public int UcnwItb { get; set; }

    public int UcnwPickUpJobId { get; set; }

    public int UcnwDeliveryJobId { get; set; }

    public DateTime? UcnwSystemDate { get; set; }

    public int? JobBookingId { get; set; }

    public string UcnwCpsignature { get; set; }

    public string WebhookAlertId { get; set; }

    public string GateNumber { get; set; }

    public int UcnwLegNumber { get; set; }

    public string UcnwAirlineName { get; set; }

    public string CarrierFsCode { get; set; }

    public string DepartureAirportFsCode { get; set; }

    public string DepartureAirportName { get; set; }

    public string DepartureAirportCity { get; set; }

    public string DepartureAirportCountry { get; set; }

    public string DepartureAirportTimeZone { get; set; }

    public string ArrivalAirportFsCode { get; set; }

    public string ArrivalAirportName { get; set; }

    public string ArrivalAirportCity { get; set; }

    public string ArrivalAirportCountry { get; set; }

    public string ArrivalAirportTimeZone { get; set; }

    public string DepartureTerminal { get; set; }

    public string ArrivalTerminal { get; set; }

    public string AircraftName { get; set; }

    public int? DepartureAirportTimeZoneId { get; set; }

    public int? ArrivalAirportTimeZoneId { get; set; }

    public virtual TimeZone ArrivalAirportTimeZoneNavigation { get; set; }

    public virtual TimeZone DepartureAirportTimeZoneNavigation { get; set; }

    public virtual TucJobBooking JobBooking { get; set; }

    public virtual ICollection<JobDeliveryJourney> JobDeliveryJourneys { get; set; } = new List<JobDeliveryJourney>();

    public virtual TucJob UcnwJob { get; set; }
}