// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucMessage
{
    public int UcmpId { get; set; }

    public DateTime? UcmpDate { get; set; }

    public int? UcmpOperator { get; set; }

    public int? UcmpCourier { get; set; }

    public string UcmpMessage { get; set; }

    public bool UcmpSent { get; set; }

    public DateTime? UcmpTime { get; set; }
}