// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucStaff
{
    public int UcstId { get; set; }

    public string UcstFirstName { get; set; }

    public string UcstLastName { get; set; }

    public DateTime? UcstStartDate { get; set; }

    public DateTime? UcstEndDate { get; set; }

    public string UcstPhone { get; set; }

    public string UcstMobile { get; set; }

    public string UcstAddress { get; set; }

    public int? UcstSuburbId { get; set; }

    public DateTime? UcstDob { get; set; }

    public string UcstNextKin { get; set; }

    public string UcstNkaddress { get; set; }

    public string UcstNkphone { get; set; }

    public string UcstIrdnumber { get; set; }

    public string UcstDoctor { get; set; }

    public string UcstDoctorPhone { get; set; }

    public int? UcstTeam { get; set; }

    public string UcstProfile { get; set; }

    public string UcstPicturePath { get; set; }

    public string UcstCode { get; set; }

    public string UcstPassword { get; set; }

    public string UcstWindowsLogonName { get; set; }

    public int? UcstDepartment { get; set; }

    public bool UcstActive { get; set; }

    public DateTime? UcstInActiveDate { get; set; }

    public string UcstInActiveSetBy { get; set; }

    public string UcstUclcode { get; set; }

    public string UcstExtension { get; set; }

    public int? StaffTitleId { get; set; }

    public string StaffDegree { get; set; }

    public string StaffBlurb { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public string ExsalerateEmail { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string AddressLine4 { get; set; }

    public string AddressLine5 { get; set; }

    public string AddressLine6 { get; set; }

    public string AddressLine7 { get; set; }

    public string AddressLine8 { get; set; }

    public virtual ICollection<JobDeliveryJourney> JobDeliveryJourneys { get; set; } = new List<JobDeliveryJourney>();

    public virtual ICollection<JobRecoveryAgent> JobRecoveryAgentCreatedByNavigations { get; set; } = new List<JobRecoveryAgent>();

    public virtual ICollection<JobRecoveryAgent> JobRecoveryAgentUpdatedByNavigations { get; set; } = new List<JobRecoveryAgent>();

    public virtual ICollection<TblBulkJobNote> TblBulkJobNoteCreatedByNavigations { get; set; } = new List<TblBulkJobNote>();

    public virtual ICollection<TblBulkJobNote> TblBulkJobNoteUpdatedByNavigations { get; set; } = new List<TblBulkJobNote>();

    public virtual ICollection<TblSetting> TblSettings { get; set; } = new List<TblSetting>();

    public virtual ICollection<TucEventAudit> TucEventAudits { get; set; } = new List<TucEventAudit>();

    public virtual ICollection<TucEvent> TucEventUcevStaffIdinNavigations { get; set; } = new List<TucEvent>();

    public virtual ICollection<TucEvent> TucEventUcevStaffIdoutNavigations { get; set; } = new List<TucEvent>();

    public virtual ICollection<TucJobBooking> TucJobBookings { get; set; } = new List<TucJobBooking>();

    public virtual ICollection<TucJobReadTracker> TucJobReadTrackers { get; set; } = new List<TucJobReadTracker>();

    public virtual ICollection<TucJob> TucJobs { get; set; } = new List<TucJob>();

    public virtual ICollection<TucManualMessage> TucManualMessageUcmmSendFromStaffs { get; set; } = new List<TucManualMessage>();

    public virtual ICollection<TucManualMessage> TucManualMessageUcmmSendToStaffs { get; set; } = new List<TucManualMessage>();

    public virtual ICollection<TucNote> TucNoteCreatedByNavigations { get; set; } = new List<TucNote>();

    public virtual ICollection<TucNote> TucNoteUpdatedByNavigations { get; set; } = new List<TucNote>();

    public virtual TucSuburb UcstSuburb { get; set; }

    public virtual ICollection<UserQuickResponse> UserQuickResponses { get; set; } = new List<UserQuickResponse>();
}