// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class TucStaff
{
    public int UcstId { get; set; }

    public string UcstFirstName { get; set; }

    public string UcstLastName { get; set; }

    public DateTime? UcstStartDate { get; set; }

    public DateTime? UcstEndDate { get; set; }

    public string UcstPhone { get; set; }

    public string UcstMobile { get; set; }

    public string UcstAddress { get; set; }

    public int? UcstSuburbId { get; set; }

    public DateTime? UcstDob { get; set; }

    public string UcstNextKin { get; set; }

    public string UcstNkaddress { get; set; }

    public string UcstNkphone { get; set; }

    public string UcstIrdnumber { get; set; }

    public string UcstDoctor { get; set; }

    public string UcstDoctorPhone { get; set; }

    public int? UcstTeam { get; set; }

    public string UcstProfile { get; set; }

    public string UcstPicturePath { get; set; }

    public string UcstCode { get; set; }

    public string UcstPassword { get; set; }

    public string UcstWindowsLogonName { get; set; }

    public int? UcstDepartment { get; set; }

    public bool UcstActive { get; set; }

    public DateTime? UcstInActiveDate { get; set; }

    public string UcstInActiveSetBy { get; set; }

    public string UcstUclcode { get; set; }

    public string UcstExtension { get; set; }

    public int? StaffTitleId { get; set; }

    public string StaffDegree { get; set; }

    public string StaffBlurb { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public string ExsalerateEmail { get; set; }

    public virtual TucSuburb UcstSuburb { get; set; }
}