// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class UnitType
{
    public int UnitTypeId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public bool Active { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual ICollection<AccessorialCharge> AccessorialChargeFreeAllowanceUnitTypes { get; set; } = new List<AccessorialCharge>();

    public virtual ICollection<AccessorialCharge> AccessorialChargeUnitTypes { get; set; } = new List<AccessorialCharge>();
}