// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class UserWidgetPreference
{
    public int UserWidgetPrefId { get; set; }

    public string UserName { get; set; }

    public int AppWidgetId { get; set; }

    public string Configuration { get; set; }

    public bool IsVisible { get; set; }

    public int Order { get; set; }

    public virtual TblAppWidget AppWidget { get; set; }
}