// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class UserDespatchViewPreference
{
    public int UserDespatchViewPrefId { get; set; }

    public int? UserId { get; set; }

    public int? DespatchViewId { get; set; }

    public bool? IsVisible { get; set; }

    public int? Order { get; set; }

    public virtual TblDespatchView DespatchView { get; set; }

    public virtual TucStaff User { get; set; }
}