// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class UserQuickResponse
{
    public int ResponseId { get; set; }

    public int? StaffId { get; set; }

    public int? CourierId { get; set; }

    public string Message { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual TucStaff Staff { get; set; }
}