// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class UTL_fncClearList_OtherResult
    {
        public int ClearListAreaID { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public int ChannelID { get; set; }
        public DateTime Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public DateTime LastModified { get; set; }
        [StringLength(50)]
        public string LastModifiedBy { get; set; }
        public string Notes { get; set; }
        public int Order { get; set; }
    }
}
