// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DespatchWeb.EntityClasses
{
    public partial class UTL_fncJob_ExtraRateResult
    {
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [Column("Fuel", TypeName = "money")]
        public decimal? Fuel { get; set; }
        [Column("DriverPay", TypeName = "money")]
        public decimal? DriverPay { get; set; }
        [Column("DriverFuel", TypeName = "money")]
        public decimal? DriverFuel { get; set; }
        [StringLength(500)]
        public string Notes { get; set; }
    }
}
