// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class UvwBookingToday
{
    public DateTime? UcbkNextDue { get; set; }

    public int UcbkId { get; set; }

    public DateTime? UcbkTime { get; set; }

    public string UcbkClientCode { get; set; }

    public string FromSuburb { get; set; }

    public string ToSuburb { get; set; }

    public string UcjtName { get; set; }

    public bool? UcbkDone { get; set; }

    public string UcbkFromAddr { get; set; }

    public string UcbkToAddr { get; set; }

    public string UcbkJobNumber { get; set; }

    public string UcbkContact { get; set; }

    public int? UcbkClientId { get; set; }

    public int? UcbkType { get; set; }

    public string Code { get; set; }
}