// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class WeightBreak
{
    public int WeightBreakId { get; set; }

    public int StartWeight { get; set; }

    public int? EndWeight { get; set; }

    public decimal? BaseCharge { get; set; }

    public decimal? ExtraWeightRate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public virtual ICollection<WeightBreakGroup> WeightBreakGroupFifthWeightBreakNavigations { get; set; } = new List<WeightBreakGroup>();

    public virtual ICollection<WeightBreakGroup> WeightBreakGroupFirstWeightBreakNavigations { get; set; } = new List<WeightBreakGroup>();

    public virtual ICollection<WeightBreakGroup> WeightBreakGroupFourthWeightBreakNavigations { get; set; } = new List<WeightBreakGroup>();

    public virtual ICollection<WeightBreakGroup> WeightBreakGroupSecondWeightBreakNavigations { get; set; } = new List<WeightBreakGroup>();

    public virtual ICollection<WeightBreakGroup> WeightBreakGroupThirdWeightBreakNavigations { get; set; } = new List<WeightBreakGroup>();
}