// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class WeightBreakGroup
{
    public int WeightBreakGroupId { get; set; }

    public string WeightBreakGroupName { get; set; }

    public int? FirstWeightBreak { get; set; }

    public int? SecondWeightBreak { get; set; }

    public int? ThirdWeightBreak { get; set; }

    public int? FourthWeightBreak { get; set; }

    public int? FifthWeightBreak { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public bool AverageWeight { get; set; }

    public virtual ICollection<AirFreightRate> AirFreightRates { get; set; } = new List<AirFreightRate>();

    public virtual WeightBreak FifthWeightBreakNavigation { get; set; }

    public virtual WeightBreak FirstWeightBreakNavigation { get; set; }

    public virtual WeightBreak FourthWeightBreakNavigation { get; set; }

    public virtual WeightBreak SecondWeightBreakNavigation { get; set; }

    public virtual WeightBreak ThirdWeightBreakNavigation { get; set; }
}