// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses;

public partial class ZoneGroup
{
    public int ZoneGroupId { get; set; }

    public string Name { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public int? ClearListAreaId { get; set; }

    public virtual TblClearListArea ClearListArea { get; set; }

    public virtual ICollection<DespatchViewZoneGroup> DespatchViewZoneGroups { get; set; } = new List<DespatchViewZoneGroup>();

    public virtual ICollection<TblDespatchView> TblDespatchViews { get; set; } = new List<TblDespatchView>();

    public virtual ICollection<ZoneName> ZoneNames { get; set; } = new List<ZoneName>();
}