// AUTO-GENERATED by scripts/generate-mui-icons-barrel.ts — do not edit. Re-emitted on every build.
// Lists every @mui/icons-material icon used under wwwroot/app/react so the
// vendor-react bundle can expose them to module bundles via window.MUIIcons.

import AcUnit from "@mui/icons-material/AcUnit";
import AccessTime from "@mui/icons-material/AccessTime";
import AccountBalance from "@mui/icons-material/AccountBalance";
import AccountBalanceWallet from "@mui/icons-material/AccountBalanceWallet";
import AccountCircle from "@mui/icons-material/AccountCircle";
import AccountTree from "@mui/icons-material/AccountTree";
import Add from "@mui/icons-material/Add";
import AddBusiness from "@mui/icons-material/AddBusiness";
import AddCircle from "@mui/icons-material/AddCircle";
import AddComment from "@mui/icons-material/AddComment";
import AirplanemodeActive from "@mui/icons-material/AirplanemodeActive";
import AirplanemodeInactive from "@mui/icons-material/AirplanemodeInactive";
import ArrowBack from "@mui/icons-material/ArrowBack";
import ArrowDownward from "@mui/icons-material/ArrowDownward";
import ArrowForward from "@mui/icons-material/ArrowForward";
import Assessment from "@mui/icons-material/Assessment";
import Assignment from "@mui/icons-material/Assignment";
import AttachFile from "@mui/icons-material/AttachFile";
import AttachMoney from "@mui/icons-material/AttachMoney";
import AutoAwesome from "@mui/icons-material/AutoAwesome";
import Badge from "@mui/icons-material/Badge";
import Bolt from "@mui/icons-material/Bolt";
import Bookmark from "@mui/icons-material/Bookmark";
import BookmarkBorder from "@mui/icons-material/BookmarkBorder";
import BugReport from "@mui/icons-material/BugReport";
import Business from "@mui/icons-material/Business";
import CalendarMonth from "@mui/icons-material/CalendarMonth";
import CalendarToday from "@mui/icons-material/CalendarToday";
import CalendarViewMonth from "@mui/icons-material/CalendarViewMonth";
import Call from "@mui/icons-material/Call";
import CallSplit from "@mui/icons-material/CallSplit";
import CameraAlt from "@mui/icons-material/CameraAlt";
import Cancel from "@mui/icons-material/Cancel";
import Category from "@mui/icons-material/Category";
import CellTower from "@mui/icons-material/CellTower";
import Chat from "@mui/icons-material/Chat";
import ChatBubbleOutline from "@mui/icons-material/ChatBubbleOutlined";
import Check from "@mui/icons-material/Check";
import CheckBox from "@mui/icons-material/CheckBox";
import CheckBoxOutlineBlank from "@mui/icons-material/CheckBoxOutlineBlank";
import CheckCircle from "@mui/icons-material/CheckCircle";
import Checklist from "@mui/icons-material/Checklist";
import ChevronLeft from "@mui/icons-material/ChevronLeft";
import ChevronRight from "@mui/icons-material/ChevronRight";
import Circle from "@mui/icons-material/Circle";
import Clear from "@mui/icons-material/Clear";
import ClearAll from "@mui/icons-material/ClearAll";
import Close from "@mui/icons-material/Close";
import CloudDownload from "@mui/icons-material/CloudDownload";
import CloudOff from "@mui/icons-material/CloudOff";
import CloudUpload from "@mui/icons-material/CloudUpload";
import ConnectingAirports from "@mui/icons-material/ConnectingAirports";
import ContactMail from "@mui/icons-material/ContactMail";
import ContactPhone from "@mui/icons-material/ContactPhone";
import Contacts from "@mui/icons-material/Contacts";
import ContentCopy from "@mui/icons-material/ContentCopy";
import Dashboard from "@mui/icons-material/Dashboard";
import DashboardCustomize from "@mui/icons-material/DashboardCustomize";
import DateRange from "@mui/icons-material/DateRange";
import Delete from "@mui/icons-material/Delete";
import DeleteSweep from "@mui/icons-material/DeleteSweep";
import DensityMedium from "@mui/icons-material/DensityMedium";
import DensitySmall from "@mui/icons-material/DensitySmall";
import Description from "@mui/icons-material/Description";
import DirectionsCar from "@mui/icons-material/DirectionsCar";
import Done from "@mui/icons-material/Done";
import DoneAll from "@mui/icons-material/DoneAll";
import DoubleArrow from "@mui/icons-material/DoubleArrow";
import Download from "@mui/icons-material/Download";
import Edit from "@mui/icons-material/Edit";
import EditNote from "@mui/icons-material/EditNote";
import Email from "@mui/icons-material/Email";
import Emergency from "@mui/icons-material/Emergency";
import Engineering from "@mui/icons-material/Engineering";
import Error from "@mui/icons-material/Error";
import ErrorOutline from "@mui/icons-material/ErrorOutlined";
import Event from "@mui/icons-material/Event";
import EventAvailable from "@mui/icons-material/EventAvailable";
import EventBusy from "@mui/icons-material/EventBusy";
import EventNote from "@mui/icons-material/EventNote";
import EventRepeat from "@mui/icons-material/EventRepeat";
import ExpandLess from "@mui/icons-material/ExpandLess";
import ExpandMore from "@mui/icons-material/ExpandMore";
import Extension from "@mui/icons-material/Extension";
import Favorite from "@mui/icons-material/Favorite";
import FileDownload from "@mui/icons-material/FileDownload";
import FilterAltOff from "@mui/icons-material/FilterAltOff";
import FirstPage from "@mui/icons-material/FirstPage";
import FitScreen from "@mui/icons-material/FitScreen";
import Flight from "@mui/icons-material/Flight";
import FlightLand from "@mui/icons-material/FlightLand";
import FlightTakeoff from "@mui/icons-material/FlightTakeoff";
import Fullscreen from "@mui/icons-material/Fullscreen";
import FullscreenExit from "@mui/icons-material/FullscreenExit";
import GpsFixed from "@mui/icons-material/GpsFixed";
import GridView from "@mui/icons-material/GridView";
import Handshake from "@mui/icons-material/Handshake";
import HelpOutline from "@mui/icons-material/HelpOutlined";
import History from "@mui/icons-material/History";
import Home from "@mui/icons-material/Home";
import Info from "@mui/icons-material/Info";
import InfoOutlined from "@mui/icons-material/InfoOutlined";
import InsertDriveFile from "@mui/icons-material/InsertDriveFile";
import Inventory from "@mui/icons-material/Inventory";
import Inventory2 from "@mui/icons-material/Inventory2";
import Inventory2Outlined from "@mui/icons-material/Inventory2Outlined";
import Label from "@mui/icons-material/Label";
import Layers from "@mui/icons-material/Layers";
import Link from "@mui/icons-material/Link";
import LocalAirport from "@mui/icons-material/LocalAirport";
import LocalShipping from "@mui/icons-material/LocalShipping";
import LocationOn from "@mui/icons-material/LocationOn";
import Lock from "@mui/icons-material/Lock";
import LockOpen from "@mui/icons-material/LockOpen";
import ManageAccounts from "@mui/icons-material/ManageAccounts";
import ManageSearch from "@mui/icons-material/ManageSearch";
import Map from "@mui/icons-material/Map";
import MarkEmailRead from "@mui/icons-material/MarkEmailRead";
import MarkEmailUnread from "@mui/icons-material/MarkEmailUnread";
import MeetingRoom from "@mui/icons-material/MeetingRoom";
import Menu from "@mui/icons-material/Menu";
import MilitaryTech from "@mui/icons-material/MilitaryTech";
import MoreVert from "@mui/icons-material/MoreVert";
import MyLocation from "@mui/icons-material/MyLocation";
import NearMe from "@mui/icons-material/NearMe";
import NightsStay from "@mui/icons-material/NightsStay";
import Note from "@mui/icons-material/Note";
import NoteAlt from "@mui/icons-material/NoteAlt";
import Notes from "@mui/icons-material/Notes";
import Notifications from "@mui/icons-material/Notifications";
import NotificationsActive from "@mui/icons-material/NotificationsActive";
import PauseCircle from "@mui/icons-material/PauseCircle";
import Payments from "@mui/icons-material/Payments";
import PendingActions from "@mui/icons-material/PendingActions";
import PeopleAlt from "@mui/icons-material/PeopleAlt";
import Person from "@mui/icons-material/Person";
import PersonAdd from "@mui/icons-material/PersonAdd";
import PersonOff from "@mui/icons-material/PersonOff";
import PersonOutline from "@mui/icons-material/PersonOutlined";
import PersonRemove from "@mui/icons-material/PersonRemove";
import PersonSearch from "@mui/icons-material/PersonSearch";
import Phone from "@mui/icons-material/Phone";
import PhoneAndroid from "@mui/icons-material/PhoneAndroid";
import PhotoCamera from "@mui/icons-material/PhotoCamera";
import PhotoLibrary from "@mui/icons-material/PhotoLibrary";
import PhotoSizeSelectLarge from "@mui/icons-material/PhotoSizeSelectLarge";
import PictureAsPdf from "@mui/icons-material/PictureAsPdf";
import PinDrop from "@mui/icons-material/PinDrop";
import Place from "@mui/icons-material/Place";
import PriceChange from "@mui/icons-material/PriceChange";
import PriceCheck from "@mui/icons-material/PriceCheck";
import PriorityHigh from "@mui/icons-material/PriorityHigh";
import Public from "@mui/icons-material/Public";
import QrCode from "@mui/icons-material/QrCode";
import QuestionMark from "@mui/icons-material/QuestionMark";
import QuickreplyOutlined from "@mui/icons-material/QuickreplyOutlined";
import Receipt from "@mui/icons-material/Receipt";
import ReceiptLong from "@mui/icons-material/ReceiptLong";
import Redo from "@mui/icons-material/Redo";
import Refresh from "@mui/icons-material/Refresh";
import Remove from "@mui/icons-material/Remove";
import Repeat from "@mui/icons-material/Repeat";
import ReportProblem from "@mui/icons-material/ReportProblem";
import RequestQuote from "@mui/icons-material/RequestQuote";
import Restore from "@mui/icons-material/Restore";
import Route from "@mui/icons-material/Route";
import SatelliteAlt from "@mui/icons-material/SatelliteAlt";
import Save from "@mui/icons-material/Save";
import Savings from "@mui/icons-material/Savings";
import Scale from "@mui/icons-material/Scale";
import Schedule from "@mui/icons-material/Schedule";
import Search from "@mui/icons-material/Search";
import SearchOff from "@mui/icons-material/SearchOff";
import SelectAll from "@mui/icons-material/SelectAll";
import Send from "@mui/icons-material/Send";
import Settings from "@mui/icons-material/Settings";
import Sms from "@mui/icons-material/Sms";
import SortByAlpha from "@mui/icons-material/SortByAlpha";
import Source from "@mui/icons-material/Source";
import Speed from "@mui/icons-material/Speed";
import Star from "@mui/icons-material/Star";
import StarBorder from "@mui/icons-material/StarBorder";
import StarRate from "@mui/icons-material/StarRate";
import StickyNote2 from "@mui/icons-material/StickyNote2";
import Stop from "@mui/icons-material/Stop";
import Straighten from "@mui/icons-material/Straighten";
import SupportAgent from "@mui/icons-material/SupportAgent";
import SwapHoriz from "@mui/icons-material/SwapHoriz";
import Sync from "@mui/icons-material/Sync";
import TableChart from "@mui/icons-material/TableChart";
import Tag from "@mui/icons-material/Tag";
import TaskAlt from "@mui/icons-material/TaskAlt";
import Terrain from "@mui/icons-material/Terrain";
import Timer from "@mui/icons-material/Timer";
import Today from "@mui/icons-material/Today";
import TrackChanges from "@mui/icons-material/TrackChanges";
import Traffic from "@mui/icons-material/Traffic";
import TrendingDown from "@mui/icons-material/TrendingDown";
import TrendingFlat from "@mui/icons-material/TrendingFlat";
import TrendingUp from "@mui/icons-material/TrendingUp";
import Tune from "@mui/icons-material/Tune";
import Update from "@mui/icons-material/Update";
import Upload from "@mui/icons-material/Upload";
import UploadFile from "@mui/icons-material/UploadFile";
import VerifiedUser from "@mui/icons-material/VerifiedUser";
import ViewAgenda from "@mui/icons-material/ViewAgenda";
import ViewCompact from "@mui/icons-material/ViewCompact";
import ViewCompactAlt from "@mui/icons-material/ViewCompactAlt";
import ViewDay from "@mui/icons-material/ViewDay";
import ViewList from "@mui/icons-material/ViewList";
import ViewWeek from "@mui/icons-material/ViewWeek";
import Visibility from "@mui/icons-material/Visibility";
import VisibilityOff from "@mui/icons-material/VisibilityOff";
import Warning from "@mui/icons-material/Warning";
import WarningAmber from "@mui/icons-material/WarningAmber";
import WarningAmberRounded from "@mui/icons-material/WarningAmberRounded";
import WifiTethering from "@mui/icons-material/WifiTethering";
import Work from "@mui/icons-material/Work";
import WorkOutline from "@mui/icons-material/WorkOutlined";
import ZoomOutMap from "@mui/icons-material/ZoomOutMap";

export const MUIIcons = {
    AcUnit,
    AccessTime,
    AccountBalance,
    AccountBalanceWallet,
    AccountCircle,
    AccountTree,
    Add,
    AddBusiness,
    AddCircle,
    AddComment,
    AirplanemodeActive,
    AirplanemodeInactive,
    ArrowBack,
    ArrowDownward,
    ArrowForward,
    Assessment,
    Assignment,
    AttachFile,
    AttachMoney,
    AutoAwesome,
    Badge,
    Bolt,
    Bookmark,
    BookmarkBorder,
    BugReport,
    Business,
    CalendarMonth,
    CalendarToday,
    CalendarViewMonth,
    Call,
    CallSplit,
    CameraAlt,
    Cancel,
    Category,
    CellTower,
    Chat,
    ChatBubbleOutline,
    Check,
    CheckBox,
    CheckBoxOutlineBlank,
    CheckCircle,
    Checklist,
    ChevronLeft,
    ChevronRight,
    Circle,
    Clear,
    ClearAll,
    Close,
    CloudDownload,
    CloudOff,
    CloudUpload,
    ConnectingAirports,
    ContactMail,
    ContactPhone,
    Contacts,
    ContentCopy,
    Dashboard,
    DashboardCustomize,
    DateRange,
    Delete,
    DeleteSweep,
    DensityMedium,
    DensitySmall,
    Description,
    DirectionsCar,
    Done,
    DoneAll,
    DoubleArrow,
    Download,
    Edit,
    EditNote,
    Email,
    Emergency,
    Engineering,
    Error,
    ErrorOutline,
    Event,
    EventAvailable,
    EventBusy,
    EventNote,
    EventRepeat,
    ExpandLess,
    ExpandMore,
    Extension,
    Favorite,
    FileDownload,
    FilterAltOff,
    FirstPage,
    FitScreen,
    Flight,
    FlightLand,
    FlightTakeoff,
    Fullscreen,
    FullscreenExit,
    GpsFixed,
    GridView,
    Handshake,
    HelpOutline,
    History,
    Home,
    Info,
    InfoOutlined,
    InsertDriveFile,
    Inventory,
    Inventory2,
    Inventory2Outlined,
    Label,
    Layers,
    Link,
    LocalAirport,
    LocalShipping,
    LocationOn,
    Lock,
    LockOpen,
    ManageAccounts,
    ManageSearch,
    Map,
    MarkEmailRead,
    MarkEmailUnread,
    MeetingRoom,
    Menu,
    MilitaryTech,
    MoreVert,
    MyLocation,
    NearMe,
    NightsStay,
    Note,
    NoteAlt,
    Notes,
    Notifications,
    NotificationsActive,
    PauseCircle,
    Payments,
    PendingActions,
    PeopleAlt,
    Person,
    PersonAdd,
    PersonOff,
    PersonOutline,
    PersonRemove,
    PersonSearch,
    Phone,
    PhoneAndroid,
    PhotoCamera,
    PhotoLibrary,
    PhotoSizeSelectLarge,
    PictureAsPdf,
    PinDrop,
    Place,
    PriceChange,
    PriceCheck,
    PriorityHigh,
    Public,
    QrCode,
    QuestionMark,
    QuickreplyOutlined,
    Receipt,
    ReceiptLong,
    Redo,
    Refresh,
    Remove,
    Repeat,
    ReportProblem,
    RequestQuote,
    Restore,
    Route,
    SatelliteAlt,
    Save,
    Savings,
    Scale,
    Schedule,
    Search,
    SearchOff,
    SelectAll,
    Send,
    Settings,
    Sms,
    SortByAlpha,
    Source,
    Speed,
    Star,
    StarBorder,
    StarRate,
    StickyNote2,
    Stop,
    Straighten,
    SupportAgent,
    SwapHoriz,
    Sync,
    TableChart,
    Tag,
    TaskAlt,
    Terrain,
    Timer,
    Today,
    TrackChanges,
    Traffic,
    TrendingDown,
    TrendingFlat,
    TrendingUp,
    Tune,
    Update,
    Upload,
    UploadFile,
    VerifiedUser,
    ViewAgenda,
    ViewCompact,
    ViewCompactAlt,
    ViewDay,
    ViewList,
    ViewWeek,
    Visibility,
    VisibilityOff,
    Warning,
    WarningAmber,
    WarningAmberRounded,
    WifiTethering,
    Work,
    WorkOutline,
    ZoomOutMap,
} as const;
