export enum JobProperty {
    ConNote = 'ConNote',
    Time = 'Time',
    Date = 'Date',
    Size = 'Size',
    Items = 'Items',
    SpeedID = 'SpeedID',
    AcceptedJobTypeID = 'AcceptedJobTypeID',
    Weight = 'Weight',
    ClientID = 'ClientID',
    ClientCode = 'ClientCode',
    ContactID = 'ContactID',
    Reprice = 'Reprice',
    Truck = 'Truck',
    Van = 'Van',
    InternalStatusID = 'InternalStatusID',
    Status = 'Status',
    RefA = 'RefA',
    RefB = 'RefB',
    OurRef = 'OurRef',
    FromContactName = 'FromContactName',
    ToContactName = 'ToContactName',
    FromContactPhone = 'FromContactPhone',
    ToContactPhone = 'ToContactPhone',
    DeliverToLeaveID = 'DeliverToLeaveID',
    Delivered = 'Delivered',
    CompletedTime = 'CompletedTime',
    DGClass = 'DGClass',
    DGDocumentation = 'DGDocumentation',
    TrackingMethod = 'TrackingMethod',
    Direct = 'Direct',
    Void = 'Void',
    TrackingMobile = 'TrackingMobile',
    TrackingEmail = 'TrackingEmail',
    PodName = 'PodName',
    Amount = 'Amount',
    Locked = 'Locked',
    PuTime = 'PuTime',
    DeliverBy = 'DeliverBy',
    BookedTime = 'BookedTime',
    FollowupTime = 'FollowupTime',
    StopDate = 'StopDate',
    RestartDate = 'RestartDate',
    InActiveDate = 'InActiveDate',
    FirstDue = 'FirstDue',
    DaysOfWeek = 'DaysOfWeek',
    Frequency = 'Frequency',
    HolidayDelivery = 'HolidayDelivery',
    CourierID = 'CourierId',
    Active = 'Active',
    DueDate = 'DueDate',
    CustomJobName = 'CustomJobName',
    TailLiftPu = 'TailLiftPu',
    TailLiftDo = 'TailLiftDo',
    DeliverToPrivateRes = 'DeliverToPrivateRes',
    Barcode = 'Barcode',
    PickupArrivalTime = 'PickupArrivalTime',
    DeliveryArrivalTime = 'DeliveryArrivalTime',
    NotifiedType = 'NotifiedType',
    AcceptedType = 'AcceptedType',
    UndeliverableLocationID = 'UndeliverableLocationID',
    // Recurring Route assignment — cascades through booking tree
    // (parent + children + grandchildren) via RecurringJobRepository's
    // ClientID-mirror branch. Backend serializes as 'RouteId'.
    RouteId = 'RouteId',
    // 3-way Assign picker (Steve 2026-05-26, HANDOVER-KEVIN-2026-05-26.md).
    // Single-row write on tucJobBooking. NpAgentId case writes BOTH
    // AgentId AND NpAgentId — handled server-side in
    // RecurringJobRepository.UpdateSimplePropertyAsync.
    AgentId = 'AgentId',
    NpAgentId = 'NpAgentId',
    // Complete flight number (e.g. 'NZ123') saved on a recurring flight
    // booking. Single-row write on tucJobBooking.SavedFlightNumber; empty
    // string clears it. Auto-assigned on push-to-live.
    SavedFlightNumber = 'SavedFlightNumber',
}
