using System;

namespace DespatchWeb.Models
{
    public partial class DirectToASAPViewModel
    {
        public int JobID { get; set; }
        public string Number { get; set; }
        public int? ClientID { get; set; }
        public int? CourierID { get; set; }
        public DateTime Date { get; set; }
        public DateTime? Time { get; set; }
        public int? JobTypeID { get; set; }
        public int? FromSuburbID { get; set; }
        public int? ToSuburbID { get; set; }
        public decimal? Amount { get; set; }
        public int Locked { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public string OurRef { get; set; }
        public bool JobDone { get; set; }
        public bool Void { get; set; }
        public string PODName { get; set; }
        public int? LatePickUp { get; set; }
        public int? LateDelivery { get; set; }
        public DateTime? CompletedTime { get; set; }
        public DateTime? DispatchDate { get; set; }
        public DateTime? DispatchTime { get; set; }
        public int? DispatcherID { get; set; }
        public bool RtnJob { get; set; }
        public int? Status { get; set; }
        public double? Weight { get; set; }
        public short? Quantity { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string Notes { get; set; }
        public string ClientReferenceA { get; set; }
        public string ClientReferenceB { get; set; }
        public string Recipient { get; set; }
        public short? Size { get; set; }
        public int? OperatorID { get; set; }
        public double? ChargeType { get; set; }
        public double? Km { get; set; }
        public double? Type { get; set; }
        public string Contact { get; set; }
        public string ToSpecial { get; set; }
        public bool CBD { get; set; }
        public string FlightDetails { get; set; }
        public bool Van { get; set; }
        public bool Attention { get; set; }
        public short? PickupFrom { get; set; }
        public int? RefJobID { get; set; }
        public string ContactPhone { get; set; }
        public int? OriginalSpeedID { get; set; }
        public int ucjbID { get; set; }
        public string ucjbNumber { get; set; }
        public DateTime ucjbDate { get; set; }
        public DateTime? ucjbTime { get; set; }
        public double? ucjbType { get; set; }
        public int? ucjbClientID { get; set; }
        public string ucjbContact { get; set; }
        public double? ucjbChargeType { get; set; }
        public decimal? ucjbAmount { get; set; }
        public int? ucjbSpeed { get; set; }
        public int? ucjbFrom { get; set; }
        public string ucjbFromAddr { get; set; }
        public int? ucjbTo { get; set; }
        public string ucjbToSpecial { get; set; }
        public string ucjbToAddr { get; set; }
        public short? ucjbSize { get; set; }
        public short? ucjbQty { get; set; }
        public bool ucjbCBD { get; set; }
        public double? ucjbKm { get; set; }
        public string ucjbFlightDetails { get; set; }
        public double? ucjbWeight { get; set; }
        public int? ucjbStatus { get; set; }
        public DateTime? ucjbDispTime { get; set; }
        public DateTime? ucjbDispDate { get; set; }
        public int? ucjbCourierID { get; set; }
        public DateTime? ucjbComplTime { get; set; }
        public bool ucjbJobDone { get; set; }
        public string ucjbClientRefa { get; set; }
        public string ucjbClientRefb { get; set; }
        public string ucjbOurRef { get; set; }
        public int? ucjbOpID { get; set; }
        public int? ucjbDispID { get; set; }
        public bool ucjbVan { get; set; }
        public bool ucjbReturn { get; set; }
        public bool ucjbVoid { get; set; }
        public bool ucjbAttention { get; set; }
        public short? ucjbPickUpFrom { get; set; }
        public bool ucjbPaged { get; set; }
        public DateTime? ucjbPagedTime { get; set; }
        public string ucjbPODName { get; set; }
        public string ucjbClientCode { get; set; }
        public int? ucjbLatePick { get; set; }
        public int? ucjbLateDel { get; set; }
        public int? ucjbRefJobID { get; set; }
        public string ucjbNotes { get; set; }
        public bool ucjbMobileSend { get; set; }
        public DateTime? ucjbSendTime { get; set; }
        public string ucjbContactPhone { get; set; }
        public bool RemoteJob { get; set; }
        public int? NumRef1 { get; set; }
        public int? NumRef2 { get; set; }
        public int? NumRef3 { get; set; }
        public int? NumRef4 { get; set; }
        public string TextRef1 { get; set; }
        public string TextRef2 { get; set; }
        public string TextRef3 { get; set; }
        public string TextRef4 { get; set; }
        public bool SaturdayDelivery { get; set; }
        public DateTime? PickUpTime { get; set; }
        public decimal RebateAmt { get; set; }
        public decimal FuelSurchargeAmount { get; set; }
        public string ClientNotes { get; set; }
        public string InternalNotes { get; set; }
        public string PickupFromContact { get; set; }
        public string PickupFromPhone { get; set; }
        public int? DeliverToPrivateBusiness { get; set; }
        public string DeliverToContact { get; set; }
        public string DeliverToPhone { get; set; }
        public int? DeliverToLeaveID { get; set; }
        public int? ProofOfDelivery { get; set; }
        public string ProofOfDeliveryEmail { get; set; }
        public string ProofOfDeliveryMobile { get; set; }
        public int? ContactID { get; set; }
        public bool LatePickupNotificationHasBeenSent { get; set; }
        public DateTime? WhenLatePickupNotificationSent { get; set; }
        public bool LateDeliveryNotificationHasBeenSent { get; set; }
        public DateTime? WhenLateDeliveryNotificationSent { get; set; }
        public bool PODNotificationHasBeenSent { get; set; }
        public DateTime? WhenPODNotificationSent { get; set; }
        public bool RatedManually { get; set; }
        public bool RuralDelivery { get; set; }
        public byte[] PickUpSignature { get; set; }
        public byte[] DeliverySignature { get; set; }
        public decimal? PickUpLongitude { get; set; }
        public decimal? PickUpLatitude { get; set; }
        public decimal? DeliveryLongitude { get; set; }
        public decimal? DeliveryLatitude { get; set; }
        public int? WaitedPickUp { get; set; }
        public int? WaitedDelivery { get; set; }
        public string PickUpName { get; set; }
        public int? DesiredJobTypeID { get; set; }
        public int? AcceptedJobTypeID { get; set; }
        public bool Direct { get; set; }
        public int? NotifiedJobTypeID { get; set; }
        public int? UndeliverableLocationID { get; set; }
        public int? JobRelationshipTypeID { get; set; }
        public int? ParentID { get; set; }
        public int? InformationParentID { get; set; }
        public int? RootParentID { get; set; }
        public int? ClosestCourierID { get; set; }
        public bool? DisplayInDespatch { get; set; }
        public int? Sequence { get; set; }
        public bool ColsolidateMarsInformation { get; set; }
        public DateTime? WhenColsolidateMarsInformation { get; set; }
        public int? ClosestCourierRule { get; set; }
        public bool? SpeedChangeNotificationHasBeenSent { get; set; }
        public DateTime? WhenSpeedChangeNotificationSent { get; set; }
        public bool? AutoDespatch { get; set; }
        public byte? PickRunOrder { get; set; }
        public byte? DropRunOrder { get; set; }
        public decimal? PPDAmount { get; set; }
        public decimal? PPDExclusiveAmount { get; set; }
        public decimal? GSTRate { get; set; }
        public bool? Truck { get; set; }
        public DateTime? TruckStartTime { get; set; }
        public double? TruckHours { get; set; }
        public DateTime? RequiredDeliveryTime { get; set; }
        public int? InternalStatus { get; set; }
        public DateTime? FollowupTime { get; set; }
        public bool? Reprice { get; set; }
        public decimal? PickupAmount { get; set; }
        public decimal? DropoffAmount { get; set; }
        public bool? BulletFreight { get; set; }
        public decimal? NWAmount { get; set; }
        public bool? VanOK { get; set; }
        public int? DGClass { get; set; }
        public bool? DGDocument { get; set; }
        public bool ItemNotReadyNotificationHasBeenSent { get; set; }
        public bool ItemNotReadyNotification { get; set; }
        public DateTime? WhenItemNotReadyNotificationSent { get; set; }
        public string ItemNotReadyNotificationNotes { get; set; }
        public bool? EmailForJobFU { get; set; }
        public string ucjbClientRefc { get; set; }
        public decimal? GSSAmount { get; set; }
        public decimal? RawAmount { get; set; }
        public string fromAddressExtras { get; set; }
        public string fromAddressStreetName { get; set; }
        public string fromAddressExtras2 { get; set; }
        public string toAddressExtras { get; set; }
        public string toAddressStreetName { get; set; }
        public string toAddressExtras2 { get; set; }
        public string GSSConnote { get; set; }
        public double? Cubic { get; set; }
        public string GssTrackingURL { get; set; }
        public decimal? PickupRawAmount { get; set; }
        public decimal? DropoffRawAmount { get; set; }
        public decimal? NWRawAmount { get; set; }
        public int? FDCourierID { get; set; }
        public bool DesCheck { get; set; }
        public bool JobTrackingNotificationHasBeenSent { get; set; }
        public DateTime? WhenJobTrackingNotificationSent { get; set; }
        public int? TrackingMethod { get; set; }
        public string TrackingMobile { get; set; }
        public string TrackingEmail { get; set; }
        public bool FirstJob { get; set; }
        public double? RunCourierPercentage { get; set; }
        public string RunName { get; set; }
        public int? FromGeoType { get; set; }
        public int? ToGeoType { get; set; }
        public int? Duration { get; set; }
        public byte[] DeliveryPhoto { get; set; }
        public string DeliveryGps { get; set; }
        public decimal? CourierPayment { get; set; }
        public decimal? RawBaseAmount { get; set; }
        public decimal? CourierBonus { get; set; }
        public int? ShopId { get; set; }
        public string ShopRef1 { get; set; }
        public string ShopRef2 { get; set; }
        public string ShopRef3 { get; set; }
        public string ShopRef4 { get; set; }
        public string ShopRef5 { get; set; }
        public DateTime? OutForDelivery { get; set; }
        public int? DepotId { get; set; }
        public string Barcode { get; set; }
        public int? StorageState { get; set; }
        public int? DeliveryState { get; set; }
        public int? Speed { get; set; }
        public string SpeedName { get; set; }
        public string DesiredSpeed { get; set; }
        public string NotifiedSpeed { get; set; }
        public string JobType { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string ExtraAddress { get; set; }
        public string SuburbFrom { get; set; }
        public string FullSuburbFrom { get; set; }
        public string SuburbTo { get; set; }
        public string FullSuburbTo { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public bool NotifyViaEmail { get; set; }
        public bool CloseEvent { get; set; }
    }
}
