//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DespatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DES_qryDespatch
    {
        public Nullable<int> ucjbClientID { get; set; }
        public string ucjbNumber { get; set; }
        public Nullable<System.DateTime> ucjbDispTime { get; set; }
        public Nullable<System.DateTime> ucjbTime { get; set; }
        public int ucjbID { get; set; }
        public Nullable<int> ucjbCourierID { get; set; }
        public string CourierCode { get; set; }
        public string SuburbFrom { get; set; }
        public string SuburbTo { get; set; }
        public Nullable<int> ucjbSpeed { get; set; }
        public Nullable<System.DateTime> ucjbComplTime { get; set; }
        public Nullable<int> ucjbDispID { get; set; }
        public bool ucjbAttention { get; set; }
        public Nullable<short> ucjbPickUpFrom { get; set; }
        public int RegionFromID { get; set; }
        public int RegionToID { get; set; }
        public bool ucjbJobDone { get; set; }
        public bool ucjbPaged { get; set; }
        public Nullable<System.DateTime> ucjbPagedTime { get; set; }
        public Nullable<int> ucjbLatePick { get; set; }
        public Nullable<int> ucjbLateDel { get; set; }
        public string ucjbContact { get; set; }
        public string ucjbToAddr { get; set; }
        public Nullable<double> ucjbType { get; set; }
        public bool ucjbVoid { get; set; }
        public bool ucjbVan { get; set; }
        public bool ucjbReturn { get; set; }
        public Nullable<System.DateTime> ucjbDispDate { get; set; }
        public Nullable<short> ucjbSize { get; set; }
        public Nullable<int> ucjbStatus { get; set; }
        public System.DateTime ucjbDate { get; set; }
        public string ucclCode { get; set; }
        public string ucjbToSpecial { get; set; }
        public string ucjsCode { get; set; }
        public bool SaturdayDelivery { get; set; }
        public Nullable<bool> EmailForJobFU { get; set; }
        public string PickupRemain { get; set; }
        public string Remain { get; set; }
        public Nullable<int> RemainTime { get; set; }
        public bool RemoteJob { get; set; }
        public string SpeedShortName { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> PickupTime { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public int AlertLatePickUp { get; set; }
        public int AlertLateDelivery { get; set; }
        public string OriginalSpeed { get; set; }
        public string ucjbPODName { get; set; }
        public string NotifiedSpeed { get; set; }
        public bool Direct { get; set; }
        public bool FirstJob { get; set; }
        public Nullable<int> NotifiedJobTypeID { get; set; }
        public int IsParentJob { get; set; }
        public Nullable<int> RootParentID { get; set; }
        public int DisplaySplitJobDetail { get; set; }
        public int DisplayReturnJobDetail { get; set; }
        public int DisplayMultiJobDetail { get; set; }
        public int IsChildJob { get; set; }
        public Nullable<bool> AllowSplit { get; set; }
        public string ChildNotes { get; set; }
        public Nullable<bool> AllowDespatch { get; set; }
        public string ClosestCourierID { get; set; }
        public Nullable<int> JobRelationshipTypeID { get; set; }
        public Nullable<int> ucclAccountStatus { get; set; }
        public Nullable<int> CDT { get; set; }
        public byte PickRunOrder { get; set; }
        public byte DropRunOrder { get; set; }
        public bool ucjbMobileSend { get; set; }
        public Nullable<bool> SendJobsViaSMS { get; set; }
        public string ucjbFromAddr { get; set; }
        public Nullable<bool> Truck { get; set; }
        public Nullable<int> InternalStatus { get; set; }
        public Nullable<System.DateTime> FollowupTime { get; set; }
        public Nullable<bool> Reprice { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<decimal> PickupAmount { get; set; }
        public Nullable<decimal> DropoffAmount { get; set; }
        public Nullable<bool> BulletFreight { get; set; }
        public Nullable<bool> VanOK { get; set; }
        public Nullable<int> DGClass { get; set; }
        public bool InternalAccount { get; set; }
        public Nullable<int> FromArea { get; set; }
        public Nullable<int> ToArea { get; set; }
        public Nullable<int> FromSuburbID { get; set; }
        public Nullable<int> ToSuburbID { get; set; }
        public bool DesCheck { get; set; }
        public Nullable<int> FDCourierID { get; set; }
        public string FDCourierCode { get; set; }
        public int HasGeoLocation { get; set; }
    }
}
