//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DespatchData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDespatchView
    {
        public int DespatchViewID { get; set; }
        public string Name { get; set; }
        public string WhereCondition { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> ShowOnDespatch { get; set; }
        public Nullable<bool> ShowOnAssistDespatch { get; set; }
        public Nullable<bool> ShowOnJobFollowup { get; set; }
    }
}
