/**
 * MUI-icon → DFRNT-icon migration map.
 *
 * The migration off `@mui/icons-material` (284 distinct glyphs) replaces each
 * icon with a Lucide (UI chrome) or Tabler (transport/logistics) equivalent,
 * rendered through the {@link Icon} wrapper. Keys are the `@mui/icons-material`
 * component names.
 *
 * This covers **every** glyph the app used before the Phase 3 sweep, so it is the
 * complete dictionary rather than a seed. `iconMap.spec.tsx` renders all of them,
 * so a bad entry is a failing test rather than a silently-missing glyph.
 *
 * ⚠️ **Do not import this at runtime.** It is one object literal over ~209
 * components, indexed dynamically, so esbuild cannot tree-shake it: a single
 * runtime importer pulls *every* glyph into that bundle. Measured at +178 KB
 * across `dist` when `SymbolIcon` briefly used it. `iconMap.spec.tsx` asserts
 * this file has no runtime importers.
 *
 * Use it as a **codemod reference**: look the MUI name up here, then import the
 * Lucide/Tabler component *directly* at the call site. Data-driven registries
 * that must map a string to a component keep their own local table of direct
 * imports — see `symbol-icon/SymbolIcon.tsx` and `task-history/eventIcons.tsx`.
 *
 * @example
 *   const {lib, component} = MUI_ICON_MAP.Close;
 *   <Icon {...{[lib]: component}} />
 */
import {
    X, Search, RefreshCw, Info, Check, CircleCheck, TriangleAlert,
    User, ChevronDown, ChevronUp, ChevronRight, Pencil, Trash2, Plus, Send, Save,
    Settings, Menu, Mail, MessageSquare, Clock, Bell,
    CircleUserRound, ChartColumn, DollarSign, Calendar, ListX, LayoutDashboard,
    LayoutGrid, FilePen, Heart, Download, UserCog, EllipsisVertical,
    CircleCheckBig, Eye, EyeOff, Phone, HardHat, Crosshair, ChevronsRight,
    CloudUpload, CloudDownload, Camera, FileUp,
    Network, Handshake, Link as LinkIcon, ListFilter, Columns3, Copy, Ban, Printer,
    ExternalLink, ArrowUpDown,
    ArrowLeft, ArrowLeftRight, ArrowRight, ArrowUp, Briefcase, Bug, Building2, CalendarCheck,
    CalendarClock, CalendarCog, CalendarDays, CalendarRange, CalendarSync, CalendarX,
    ChartNoAxesGantt, CheckCheck, ChevronLeft, Circle, CircleAlert, CircleDollarSign,
    CirclePause, CirclePlay, CirclePlus, ClipboardList, CreditCard, DoorOpen, FilePlus,
    FileText, Filter, FilterX, Flag, Folder, Gauge, GlobeLock, Headset, IdCard, Image, Inbox,
    Landmark, Layers, List, LocateFixed, Lock, LockOpen, Maximize, MessageCircle,
    MessageSquarePlus, MessageSquareReply, Minimize, Minus, Moon, Mountain, MoveRight,
    Navigation, NotebookPen, NotebookText, PenTool, PhoneCall, Play, Power, QrCode, ReceiptText,
    RefreshCcwDot, Rocket, Rows3, Rss, Ruler, Satellite, Scale, Scan, ScanText, ScrollText,
    SearchX, Shapes, ShieldCheck, ShoppingCart, Shuffle, Siren, SlidersHorizontal, Smartphone,
    Sparkles, Square, SquareCheck, SquareCheckBig, StickyNote, Store, Tag, TrafficCone,
    TrendingDown, TrendingUp, Undo2, Upload, UserSearch, UserX, Users, Wallet, Wrench
} from 'lucide-react';
import {
    IconTruck, IconPlane, IconPlaneOff, IconMapPin, IconRoute, IconPackage, IconMap,
    IconPlaneDeparture, IconPlaneArrival, IconSnowflake, IconQuestionMark,
    IconBuildingWarehouse, IconBus, IconCar, IconPlaneTilt, IconUserPin
} from '@tabler/icons-react';
import type {LucideIcon, TablerIcon} from './Icon';

/**
 * Discriminated union so `component`'s type is narrowed by `lib` — a `lucide`
 * entry carries a Lucide icon, a `tabler` entry a Tabler icon (their stroke
 * props differ, so they can't share one type). See {@link Icon}.
 */
export type IconMapEntry =
    | {lib: 'lucide'; component: LucideIcon}
    | {lib: 'tabler'; component: TablerIcon};

export const MUI_ICON_MAP: Record<string, IconMapEntry> = {
    // ── Lucide: generic UI chrome ────────────────────────────────────────
    Close: {lib: 'lucide', component: X},
    Search: {lib: 'lucide', component: Search},
    Refresh: {lib: 'lucide', component: RefreshCw},
    Info: {lib: 'lucide', component: Info},
    Check: {lib: 'lucide', component: Check},
    CheckCircle: {lib: 'lucide', component: CircleCheck},
    Warning: {lib: 'lucide', component: TriangleAlert},
    Person: {lib: 'lucide', component: User},
    ExpandMore: {lib: 'lucide', component: ChevronDown},
    ExpandLess: {lib: 'lucide', component: ChevronUp},
    Edit: {lib: 'lucide', component: Pencil},
    Delete: {lib: 'lucide', component: Trash2},
    Add: {lib: 'lucide', component: Plus},
    Send: {lib: 'lucide', component: Send},
    Save: {lib: 'lucide', component: Save},
    Settings: {lib: 'lucide', component: Settings},
    Menu: {lib: 'lucide', component: Menu},
    Email: {lib: 'lucide', component: Mail},
    Sms: {lib: 'lucide', component: MessageSquare},
    Schedule: {lib: 'lucide', component: Clock},
    AccessTime: {lib: 'lucide', component: Clock},
    Notifications: {lib: 'lucide', component: Bell},
    AccountCircle: {lib: 'lucide', component: CircleUserRound},
    Assessment: {lib: 'lucide', component: ChartColumn},
    AttachMoney: {lib: 'lucide', component: DollarSign},
    CalendarTodayOutlined: {lib: 'lucide', component: Calendar},
    ClearAll: {lib: 'lucide', component: ListX},
    Dashboard: {lib: 'lucide', component: LayoutDashboard},
    DashboardCustomize: {lib: 'lucide', component: LayoutGrid},
    Done: {lib: 'lucide', component: Check},
    DriveFileRenameOutline: {lib: 'lucide', component: FilePen},
    Favorite: {lib: 'lucide', component: Heart},
    FileDownload: {lib: 'lucide', component: Download},
    ManageAccounts: {lib: 'lucide', component: UserCog},
    MoreVert: {lib: 'lucide', component: EllipsisVertical},
    NavigateNext: {lib: 'lucide', component: ChevronRight},
    TaskAlt: {lib: 'lucide', component: CircleCheckBig},
    Visibility: {lib: 'lucide', component: Eye},
    VisibilityOff: {lib: 'lucide', component: EyeOff},
    Phone: {lib: 'lucide', component: Phone},
    Engineering: {lib: 'lucide', component: HardHat},
    MyLocation: {lib: 'lucide', component: Crosshair},
    DoubleArrow: {lib: 'lucide', component: ChevronsRight},
    CloudUpload: {lib: 'lucide', component: CloudUpload},
    CloudDownload: {lib: 'lucide', component: CloudDownload},
    CameraAlt: {lib: 'lucide', component: Camera},
    UploadFile: {lib: 'lucide', component: FileUp},
    AccountTree: {lib: 'lucide', component: Network},
    Handshake: {lib: 'lucide', component: Handshake},
    Link: {lib: 'lucide', component: LinkIcon},
    FilterList: {lib: 'lucide', component: ListFilter},
    ViewColumn: {lib: 'lucide', component: Columns3},
    ContentCopy: {lib: 'lucide', component: Copy},
    Cancel: {lib: 'lucide', component: Ban},
    Print: {lib: 'lucide', component: Printer},
    OpenInNew: {lib: 'lucide', component: ExternalLink},
    Sort: {lib: 'lucide', component: ArrowUpDown},

    // ── Tabler: transport & logistics ────────────────────────────────────
    LocalShipping: {lib: 'tabler', component: IconTruck},
    Flight: {lib: 'tabler', component: IconPlane},
    AirplanemodeActive: {lib: 'tabler', component: IconPlane},
    AirplanemodeInactive: {lib: 'tabler', component: IconPlaneOff},
    LocationOn: {lib: 'tabler', component: IconMapPin},
    Place: {lib: 'tabler', component: IconMapPin},
    Route: {lib: 'tabler', component: IconRoute},
    Inventory2: {lib: 'tabler', component: IconPackage},
    Map: {lib: 'tabler', component: IconMap},
    FlightTakeoff: {lib: 'tabler', component: IconPlaneDeparture},
    FlightLand: {lib: 'tabler', component: IconPlaneArrival},
    LocalAirport: {lib: 'tabler', component: IconPlane},
    AcUnit: {lib: 'tabler', component: IconSnowflake},
    QuestionMark: {lib: 'tabler', component: IconQuestionMark},

    // ── Phase 3 sweep: the remaining glyphs ─────────────────────────────
    AccountBalance: {lib: 'lucide', component: Landmark},
    AccountBalanceWallet: {lib: 'lucide', component: Wallet},
    AddBusiness: {lib: 'lucide', component: Store},
    AddCircle: {lib: 'lucide', component: CirclePlus},
    AddComment: {lib: 'lucide', component: MessageSquarePlus},
    ArrowBack: {lib: 'lucide', component: ArrowLeft},
    ArrowDropDown: {lib: 'lucide', component: ChevronDown},
    ArrowForward: {lib: 'lucide', component: ArrowRight},
    Assignment: {lib: 'lucide', component: ClipboardList},
    AutoAwesome: {lib: 'lucide', component: Sparkles},
    Autorenew: {lib: 'lucide', component: RefreshCw},
    Badge: {lib: 'lucide', component: IdCard},
    Block: {lib: 'lucide', component: Ban},
    BugReport: {lib: 'lucide', component: Bug},
    Build: {lib: 'lucide', component: Wrench},
    Business: {lib: 'lucide', component: Building2},
    CalendarMonth: {lib: 'lucide', component: Calendar},
    CalendarViewMonth: {lib: 'lucide', component: Columns3},
    Category: {lib: 'lucide', component: Shapes},
    Chat: {lib: 'lucide', component: MessageSquare},
    ChatBubbleOutlined: {lib: 'lucide', component: MessageCircle},
    CheckBox: {lib: 'lucide', component: SquareCheck},
    CheckBoxOutlineBlank: {lib: 'lucide', component: Square},
    ChevronLeft: {lib: 'lucide', component: ChevronLeft},
    ChevronRight: {lib: 'lucide', component: ChevronRight},
    Circle: {lib: 'lucide', component: Circle},
    Clear: {lib: 'lucide', component: X},
    ContactMail: {lib: 'lucide', component: Mail},
    ContactPhone: {lib: 'lucide', component: PhoneCall},
    CropSquare: {lib: 'lucide', component: Square},
    DateRange: {lib: 'lucide', component: CalendarRange},
    Description: {lib: 'lucide', component: FileText},
    DocumentScanner: {lib: 'lucide', component: ScanText},
    DoneAll: {lib: 'lucide', component: CheckCheck},
    Download: {lib: 'lucide', component: Download},
    Draw: {lib: 'lucide', component: PenTool},
    EditCalendar: {lib: 'lucide', component: CalendarCog},
    EditNote: {lib: 'lucide', component: NotebookPen},
    Emergency: {lib: 'lucide', component: Siren},
    EngineeringOutlined: {lib: 'lucide', component: HardHat},
    Error: {lib: 'lucide', component: CircleAlert},
    ErrorOutlined: {lib: 'lucide', component: CircleAlert},
    Event: {lib: 'lucide', component: CalendarDays},
    EventBusy: {lib: 'lucide', component: CalendarX},
    EventNote: {lib: 'lucide', component: CalendarClock},
    EventRepeat: {lib: 'lucide', component: CalendarSync},
    FilterAlt: {lib: 'lucide', component: Filter},
    FilterAltOff: {lib: 'lucide', component: FilterX},
    FitScreen: {lib: 'lucide', component: Scan},
    Flag: {lib: 'lucide', component: Flag},
    FormatListBulleted: {lib: 'lucide', component: List},
    Fullscreen: {lib: 'lucide', component: Maximize},
    FullscreenExit: {lib: 'lucide', component: Minimize},
    GpsFixed: {lib: 'lucide', component: LocateFixed},
    GridView: {lib: 'lucide', component: LayoutGrid},
    HistoryEdu: {lib: 'lucide', component: ScrollText},
    InfoOutlined: {lib: 'lucide', component: Info},
    Landscape: {lib: 'lucide', component: Image},
    Layers: {lib: 'lucide', component: Layers},
    ListAlt: {lib: 'lucide', component: List},
    Lock: {lib: 'lucide', component: Lock},
    LockOpen: {lib: 'lucide', component: LockOpen},
    LockOutlined: {lib: 'lucide', component: Lock},
    MeetingRoom: {lib: 'lucide', component: DoorOpen},
    NearMe: {lib: 'lucide', component: Navigation},
    NightsStay: {lib: 'lucide', component: Moon},
    Note: {lib: 'lucide', component: StickyNote},
    NoteAdd: {lib: 'lucide', component: FilePlus},
    Notes: {lib: 'lucide', component: NotebookText},
    Paid: {lib: 'lucide', component: CircleDollarSign},
    PauseCircle: {lib: 'lucide', component: CirclePause},
    Payments: {lib: 'lucide', component: CreditCard},
    PeopleAlt: {lib: 'lucide', component: Users},
    PersonOffOutlined: {lib: 'lucide', component: UserX},
    PersonSearch: {lib: 'lucide', component: UserSearch},
    PlayArrow: {lib: 'lucide', component: Play},
    PlayCircleOutlined: {lib: 'lucide', component: CirclePlay},
    PowerSettingsNew: {lib: 'lucide', component: Power},
    PriorityHigh: {lib: 'lucide', component: TriangleAlert},
    PublicOff: {lib: 'lucide', component: GlobeLock},
    PublishedWithChanges: {lib: 'lucide', component: RefreshCcwDot},
    QrCode2: {lib: 'lucide', component: QrCode},
    QuickreplyOutlined: {lib: 'lucide', component: MessageSquareReply},
    ReceiptLong: {lib: 'lucide', component: ReceiptText},
    Remove: {lib: 'lucide', component: Minus},
    ReportProblem: {lib: 'lucide', component: TriangleAlert},
    RequestQuote: {lib: 'lucide', component: FileText},
    RocketLaunch: {lib: 'lucide', component: Rocket},
    SatelliteAlt: {lib: 'lucide', component: Satellite},
    Scale: {lib: 'lucide', component: Scale},
    SearchOff: {lib: 'lucide', component: SearchX},
    SearchOffOutlined: {lib: 'lucide', component: SearchX},
    SendToMobile: {lib: 'lucide', component: Smartphone},
    ShoppingCart: {lib: 'lucide', component: ShoppingCart},
    Shuffle: {lib: 'lucide', component: Shuffle},
    Speed: {lib: 'lucide', component: Gauge},
    StickyNote2: {lib: 'lucide', component: StickyNote},
    Stop: {lib: 'lucide', component: Square},
    Straight: {lib: 'lucide', component: ArrowUp},
    Straighten: {lib: 'lucide', component: Ruler},
    SupportAgent: {lib: 'lucide', component: Headset},
    SwapCalls: {lib: 'lucide', component: ArrowLeftRight},
    SwapHoriz: {lib: 'lucide', component: ArrowLeftRight},
    Sync: {lib: 'lucide', component: RefreshCw},
    Tag: {lib: 'lucide', component: Tag},
    Task: {lib: 'lucide', component: SquareCheckBig},
    Terrain: {lib: 'lucide', component: Mountain},
    Timeline: {lib: 'lucide', component: ChartNoAxesGantt},
    Today: {lib: 'lucide', component: CalendarCheck},
    Topic: {lib: 'lucide', component: Folder},
    Traffic: {lib: 'lucide', component: TrafficCone},
    TrendingDown: {lib: 'lucide', component: TrendingDown},
    TrendingFlat: {lib: 'lucide', component: MoveRight},
    TrendingUp: {lib: 'lucide', component: TrendingUp},
    Tune: {lib: 'lucide', component: SlidersHorizontal},
    Undo: {lib: 'lucide', component: Undo2},
    Upcoming: {lib: 'lucide', component: Inbox},
    Update: {lib: 'lucide', component: RefreshCw},
    Upload: {lib: 'lucide', component: Upload},
    VerifiedUser: {lib: 'lucide', component: ShieldCheck},
    ViewDay: {lib: 'lucide', component: Rows3},
    ViewList: {lib: 'lucide', component: List},
    ViewWeek: {lib: 'lucide', component: Columns3},
    WarningAmber: {lib: 'lucide', component: TriangleAlert},
    WarningAmberRounded: {lib: 'lucide', component: TriangleAlert},
    WifiTethering: {lib: 'lucide', component: Rss},
    WorkOutlined: {lib: 'lucide', component: Briefcase},
    ZoomOutMap: {lib: 'lucide', component: Maximize},

    // ── Phase 3 sweep: transport & logistics ────────────────────────────
    AirportShuttle: {lib: 'tabler', component: IconBus},
    ConnectingAirports: {lib: 'tabler', component: IconPlaneTilt},
    DirectionsCar: {lib: 'tabler', component: IconCar},
    FlightTakeoffOutlined: {lib: 'tabler', component: IconPlaneDeparture},
    Inventory: {lib: 'tabler', component: IconPackage},
    Inventory2Outlined: {lib: 'tabler', component: IconPackage},
    LocalAirportOutlined: {lib: 'tabler', component: IconPlane},
    PersonPinCircleOutlined: {lib: 'tabler', component: IconUserPin},
    PinDrop: {lib: 'tabler', component: IconMapPin},
    Warehouse: {lib: 'tabler', component: IconBuildingWarehouse},
};

export default MUI_ICON_MAP;
