//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'DesQryAllJobType'.</summary>
	public partial class DesQryAllJobType : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="DesQryAllJobType"/> class.</summary>
		public DesQryAllJobType() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the JobTypeId field. </summary>
		public System.Int32 JobTypeId { get; set;}
		/// <summary>Gets or sets the Name field. </summary>
		public System.String Name { get; set;}
	}
}
