//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TblClientContact'.</summary>
	public partial class TblClientContact : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblClientContact"/> class.</summary>
		public TblClientContact() : base()
		{
			this.TblClientContactInternetPermissions = new List<TblClientContactInternetPermission>();
			OnCreated();
		}

		/// <summary>Gets or sets the AddOnCharge field. </summary>
		public System.Boolean AddOnCharge { get; set;}
		/// <summary>Gets or sets the ClientContactId field. </summary>
		public System.Int32 ClientContactId { get; set;}
		/// <summary>Gets or sets the ClientId field. </summary>
		public System.Int32 ClientId { get; set;}
		/// <summary>Gets or sets the ContactId field. </summary>
		public System.Int32 ContactId { get; set;}
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the DefaultClientAddressBookId field. </summary>
		public Nullable<System.Int32> DefaultClientAddressBookId { get; set;}
		/// <summary>Gets or sets the DefaultJobSize field. </summary>
		public System.String DefaultJobSize { get; set;}
		/// <summary>Gets or sets the DefaultJobSpeed field. </summary>
		public System.String DefaultJobSpeed { get; set;}
		/// <summary>Gets or sets the DefaultJobType field. </summary>
		public System.String DefaultJobType { get; set;}
		/// <summary>Gets or sets the DefaultPage field. </summary>
		public System.String DefaultPage { get; set;}
		/// <summary>Gets or sets the DefaultPickupLocation field. </summary>
		public System.String DefaultPickupLocation { get; set;}
		/// <summary>Gets or sets the DefaultPod field. </summary>
		public Nullable<System.Int32> DefaultPod { get; set;}
		/// <summary>Gets or sets the DefaultPodemail field. </summary>
		public System.String DefaultPodemail { get; set;}
		/// <summary>Gets or sets the DefaultPodphone field. </summary>
		public System.String DefaultPodphone { get; set;}
		/// <summary>Gets or sets the DefaultPrinter field. </summary>
		public System.String DefaultPrinter { get; set;}
		/// <summary>Gets or sets the DefaultPrintSize field. </summary>
		public Nullable<System.Int32> DefaultPrintSize { get; set;}
		/// <summary>Gets or sets the DefaultRotate180 field. </summary>
		public Nullable<System.Boolean> DefaultRotate180 { get; set;}
		/// <summary>Gets or sets the DefaultSendTrackAndTraceToPodemail field. </summary>
		public Nullable<System.Boolean> DefaultSendTrackAndTraceToPodemail { get; set;}
		/// <summary>Gets or sets the DefaultTrackingEmail field. </summary>
		public System.String DefaultTrackingEmail { get; set;}
		/// <summary>Gets or sets the DefaultTrackingMethod field. </summary>
		public Nullable<System.Int32> DefaultTrackingMethod { get; set;}
		/// <summary>Gets or sets the DefaultTrackingMobile field. </summary>
		public System.String DefaultTrackingMobile { get; set;}
		/// <summary>Gets or sets the HoldJobs field. </summary>
		public System.Boolean HoldJobs { get; set;}
		/// <summary>Gets or sets the IsDefaultAccount field. </summary>
		public System.Boolean IsDefaultAccount { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the MaxJobSpend field. </summary>
		public Nullable<System.Decimal> MaxJobSpend { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the RotateLabel field. </summary>
		public System.Boolean RotateLabel { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblClientContactInternetPermission.TblClientContact - TblClientContact.TblClientContactInternetPermissions (m:1)'</summary>
		public virtual List<TblClientContactInternetPermission> TblClientContactInternetPermissions { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblClientContact.TucClient - TucClient.TblClientContacts (m:1)'</summary>
		public virtual TucClient TucClient { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblClientContact.TucClientContact - TucClientContact.TblClientContacts (m:1)'</summary>
		public virtual TucClientContact TucClientContact { get; set;}
	}
}
