//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TblCourier'.</summary>
	public partial class TblCourier : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblCourier"/> class.</summary>
		public TblCourier() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AccountProfileId field. </summary>
		public Nullable<System.Int32> AccountProfileId { get; set;}
		/// <summary>Gets or sets the Active field. </summary>
		public System.Boolean Active { get; set;}
		/// <summary>Gets or sets the Address field. </summary>
		public System.String Address { get; set;}
		/// <summary>Gets or sets the AfterHoursWeb field. </summary>
		public Nullable<System.Boolean> AfterHoursWeb { get; set;}
		/// <summary>Gets or sets the AutoDespatch field. </summary>
		public System.Boolean AutoDespatch { get; set;}
		/// <summary>Gets or sets the BankAccountNumber field. </summary>
		public System.String BankAccountNumber { get; set;}
		/// <summary>Gets or sets the BankBranch field. </summary>
		public System.String BankBranch { get; set;}
		/// <summary>Gets or sets the BankNameId field. </summary>
		public Nullable<System.Int32> BankNameId { get; set;}
		/// <summary>Gets or sets the Blurb field. </summary>
		public System.String Blurb { get; set;}
		/// <summary>Gets or sets the CarrierLiabilityId field. </summary>
		public Nullable<System.Int32> CarrierLiabilityId { get; set;}
		/// <summary>Gets or sets the CarSavingsAmount field. </summary>
		public Nullable<System.Decimal> CarSavingsAmount { get; set;}
		/// <summary>Gets or sets the CarSavingsEnd field. </summary>
		public Nullable<System.DateTime> CarSavingsEnd { get; set;}
		/// <summary>Gets or sets the CarSavingsStart field. </summary>
		public Nullable<System.DateTime> CarSavingsStart { get; set;}
		/// <summary>Gets or sets the ChannelId field. </summary>
		public Nullable<System.Int32> ChannelId { get; set;}
		/// <summary>Gets or sets the Code field. </summary>
		public System.String Code { get; set;}
		/// <summary>Gets or sets the CommercialInsurance field. </summary>
		public Nullable<System.Boolean> CommercialInsurance { get; set;}
		/// <summary>Gets or sets the ContractSignedDate field. </summary>
		public Nullable<System.DateTime> ContractSignedDate { get; set;}
		/// <summary>Gets or sets the CourierFleetId field. </summary>
		public Nullable<System.Int32> CourierFleetId { get; set;}
		/// <summary>Gets or sets the CourierGpsid field. </summary>
		public Nullable<System.Int32> CourierGpsid { get; set;}
		/// <summary>Gets or sets the CourierId field. </summary>
		public System.Int32 CourierId { get; set;}
		/// <summary>Gets or sets the CourierLogInOutId field. </summary>
		public Nullable<System.Int32> CourierLogInOutId { get; set;}
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the CustomField1 field. </summary>
		public System.String CustomField1 { get; set;}
		/// <summary>Gets or sets the CustomField2 field. </summary>
		public System.String CustomField2 { get; set;}
		/// <summary>Gets or sets the CustomField3 field. </summary>
		public System.String CustomField3 { get; set;}
		/// <summary>Gets or sets the DangerousGoods field. </summary>
		public System.Byte DangerousGoods { get; set;}
		/// <summary>Gets or sets the DateOfBirth field. </summary>
		public Nullable<System.DateTime> DateOfBirth { get; set;}
		/// <summary>Gets or sets the DeviceAdmin field. </summary>
		public Nullable<System.Boolean> DeviceAdmin { get; set;}
		/// <summary>Gets or sets the DeviceTypeId field. </summary>
		public Nullable<System.Int32> DeviceTypeId { get; set;}
		/// <summary>Gets or sets the DglicenseExpiry field. </summary>
		public Nullable<System.DateTime> DglicenseExpiry { get; set;}
		/// <summary>Gets or sets the DisplayWeb field. </summary>
		public System.Boolean DisplayWeb { get; set;}
		/// <summary>Gets or sets the Doctor field. </summary>
		public System.String Doctor { get; set;}
		/// <summary>Gets or sets the DoctorPhone field. </summary>
		public System.String DoctorPhone { get; set;}
		/// <summary>Gets or sets the DriversLicenceNumber field. </summary>
		public System.String DriversLicenceNumber { get; set;}
		/// <summary>Gets or sets the DriversLicenseExpiry field. </summary>
		public Nullable<System.DateTime> DriversLicenseExpiry { get; set;}
		/// <summary>Gets or sets the Email field. </summary>
		public System.String Email { get; set;}
		/// <summary>Gets or sets the ExpectedEndTime field. </summary>
		public Nullable<System.DateTime> ExpectedEndTime { get; set;}
		/// <summary>Gets or sets the ExpectedStartTime field. </summary>
		public Nullable<System.DateTime> ExpectedStartTime { get; set;}
		/// <summary>Gets or sets the FinishDate field. </summary>
		public Nullable<System.DateTime> FinishDate { get; set;}
		/// <summary>Gets or sets the FirstName field. </summary>
		public System.String FirstName { get; set;}
		/// <summary>Gets or sets the Gender field. </summary>
		public Nullable<System.Boolean> Gender { get; set;}
		/// <summary>Gets or sets the GoodsServiceLicenceNumber field. </summary>
		public System.String GoodsServiceLicenceNumber { get; set;}
		/// <summary>Gets or sets the GstregistrationNumber field. </summary>
		public System.String GstregistrationNumber { get; set;}
		/// <summary>Gets or sets the HeavyTransportEndorcement field. </summary>
		public Nullable<System.Boolean> HeavyTransportEndorcement { get; set;}
		/// <summary>Gets or sets the Height field. </summary>
		public Nullable<System.Double> Height { get; set;}
		/// <summary>Gets or sets the HomePhone field. </summary>
		public System.String HomePhone { get; set;}
		/// <summary>Gets or sets the InsuranceCompanyId field. </summary>
		public Nullable<System.Int32> InsuranceCompanyId { get; set;}
		/// <summary>Gets or sets the Internal field. </summary>
		public System.Boolean Internal { get; set;}
		/// <summary>Gets or sets the JobPaperPrintOut field. </summary>
		public System.Boolean JobPaperPrintOut { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the LateNightId field. </summary>
		public Nullable<System.Int32> LateNightId { get; set;}
		/// <summary>Gets or sets the Length field. </summary>
		public Nullable<System.Double> Length { get; set;}
		/// <summary>Gets or sets the LowEmissionVehicle field. </summary>
		public Nullable<System.Boolean> LowEmissionVehicle { get; set;}
		/// <summary>Gets or sets the Macourier field. </summary>
		public System.Boolean Macourier { get; set;}
		/// <summary>Gets or sets the MaxPallets field. </summary>
		public Nullable<System.Int32> MaxPallets { get; set;}
		/// <summary>Gets or sets the MaxPayLoad field. </summary>
		public Nullable<System.Double> MaxPayLoad { get; set;}
		/// <summary>Gets or sets the Mobile field. </summary>
		public System.String Mobile { get; set;}
		/// <summary>Gets or sets the MobileAdAmount field. </summary>
		public Nullable<System.Decimal> MobileAdAmount { get; set;}
		/// <summary>Gets or sets the MobileAdEnd field. </summary>
		public Nullable<System.DateTime> MobileAdEnd { get; set;}
		/// <summary>Gets or sets the MobileAdStart field. </summary>
		public Nullable<System.DateTime> MobileAdStart { get; set;}
		/// <summary>Gets or sets the MobileInsurance field. </summary>
		public Nullable<System.Decimal> MobileInsurance { get; set;}
		/// <summary>Gets or sets the MobileRental field. </summary>
		public Nullable<System.Decimal> MobileRental { get; set;}
		/// <summary>Gets or sets the NextOfKin field. </summary>
		public System.String NextOfKin { get; set;}
		/// <summary>Gets or sets the NextOfKinAddress field. </summary>
		public System.String NextOfKinAddress { get; set;}
		/// <summary>Gets or sets the NextOfKinPhone field. </summary>
		public System.String NextOfKinPhone { get; set;}
		/// <summary>Gets or sets the NextOfKinRelationship field. </summary>
		public System.String NextOfKinRelationship { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the PagerId field. </summary>
		public Nullable<System.Double> PagerId { get; set;}
		/// <summary>Gets or sets the PagerSerial field. </summary>
		public System.String PagerSerial { get; set;}
		/// <summary>Gets or sets the Password field. </summary>
		public System.String Password { get; set;}
		/// <summary>Gets or sets the PaydayFileRegistration field. </summary>
		public Nullable<System.Boolean> PaydayFileRegistration { get; set;}
		/// <summary>Gets or sets the Percentage field. </summary>
		public Nullable<System.Double> Percentage { get; set;}
		/// <summary>Gets or sets the PersonalMobile field. </summary>
		public System.String PersonalMobile { get; set;}
		/// <summary>Gets or sets the PicturePath field. </summary>
		public System.String PicturePath { get; set;}
		/// <summary>Gets or sets the Podreqd field. </summary>
		public Nullable<System.Boolean> Podreqd { get; set;}
		/// <summary>Gets or sets the PolicyNumber field. </summary>
		public System.String PolicyNumber { get; set;}
		/// <summary>Gets or sets the Profile field. </summary>
		public System.String Profile { get; set;}
		/// <summary>Gets or sets the PublicLiabilityId field. </summary>
		public Nullable<System.Int32> PublicLiabilityId { get; set;}
		/// <summary>Gets or sets the RegistrationExpiry field. </summary>
		public Nullable<System.DateTime> RegistrationExpiry { get; set;}
		/// <summary>Gets or sets the Rtserial field. </summary>
		public System.String Rtserial { get; set;}
		/// <summary>Gets or sets the Rttype field. </summary>
		public System.String Rttype { get; set;}
		/// <summary>Gets or sets the Ruckms field. </summary>
		public Nullable<System.Double> Ruckms { get; set;}
		/// <summary>Gets or sets the Rucpayload field. </summary>
		public Nullable<System.Double> Rucpayload { get; set;}
		/// <summary>Gets or sets the Rucweight field. </summary>
		public Nullable<System.Double> Rucweight { get; set;}
		/// <summary>Gets or sets the SecurityCheckDate field. </summary>
		public Nullable<System.DateTime> SecurityCheckDate { get; set;}
		/// <summary>Gets or sets the SendAlertSms field. </summary>
		public System.Boolean SendAlertSms { get; set;}
		/// <summary>Gets or sets the SendJobsViaSms field. </summary>
		public System.Boolean SendJobsViaSms { get; set;}
		/// <summary>Gets or sets the ShowClientPhone field. </summary>
		public System.Boolean ShowClientPhone { get; set;}
		/// <summary>Gets or sets the SiteId field. </summary>
		public Nullable<System.Int32> SiteId { get; set;}
		/// <summary>Gets or sets the StartDate field. </summary>
		public Nullable<System.DateTime> StartDate { get; set;}
		/// <summary>Gets or sets the Surname field. </summary>
		public System.String Surname { get; set;}
		/// <summary>Gets or sets the TareWeight field. </summary>
		public Nullable<System.Double> TareWeight { get; set;}
		/// <summary>Gets or sets the TaxSavingsEnd field. </summary>
		public Nullable<System.DateTime> TaxSavingsEnd { get; set;}
		/// <summary>Gets or sets the TaxSavingsStart field. </summary>
		public Nullable<System.DateTime> TaxSavingsStart { get; set;}
		/// <summary>Gets or sets the Team field. </summary>
		public Nullable<System.Int32> Team { get; set;}
		/// <summary>Gets or sets the TrainingHr field. </summary>
		public System.String TrainingHr { get; set;}
		/// <summary>Gets or sets the TrainingHrFu field. </summary>
		public System.String TrainingHrFu { get; set;}
		/// <summary>Gets or sets the UccrAddress field. </summary>
		public System.String UccrAddress { get; set;}
		/// <summary>Gets or sets the UccrBankAccountNo field. </summary>
		public System.String UccrBankAccountNo { get; set;}
		/// <summary>Gets or sets the UccrBankBranch field. </summary>
		public System.String UccrBankBranch { get; set;}
		/// <summary>Gets or sets the UccrBankNameId field. </summary>
		public Nullable<System.Int32> UccrBankNameId { get; set;}
		/// <summary>Gets or sets the UccrCarrierLiabilityId field. </summary>
		public Nullable<System.Int32> UccrCarrierLiabilityId { get; set;}
		/// <summary>Gets or sets the UccrChannelId field. </summary>
		public Nullable<System.Int32> UccrChannelId { get; set;}
		/// <summary>Gets or sets the UccrContractDate field. </summary>
		public Nullable<System.DateTime> UccrContractDate { get; set;}
		/// <summary>Gets or sets the UccrCustomField1 field. </summary>
		public System.String UccrCustomField1 { get; set;}
		/// <summary>Gets or sets the UccrCustomField2 field. </summary>
		public System.String UccrCustomField2 { get; set;}
		/// <summary>Gets or sets the UccrCustomField3 field. </summary>
		public System.String UccrCustomField3 { get; set;}
		/// <summary>Gets or sets the UccrDangerousGoods field. </summary>
		public System.Byte UccrDangerousGoods { get; set;}
		/// <summary>Gets or sets the UccrDlno field. </summary>
		public System.String UccrDlno { get; set;}
		/// <summary>Gets or sets the UccrDob field. </summary>
		public Nullable<System.DateTime> UccrDob { get; set;}
		/// <summary>Gets or sets the UccrDoctor field. </summary>
		public System.String UccrDoctor { get; set;}
		/// <summary>Gets or sets the UccrDoctorPhone field. </summary>
		public System.String UccrDoctorPhone { get; set;}
		/// <summary>Gets or sets the UccrEmail field. </summary>
		public System.String UccrEmail { get; set;}
		/// <summary>Gets or sets the UccrFinishDate field. </summary>
		public Nullable<System.DateTime> UccrFinishDate { get; set;}
		/// <summary>Gets or sets the UccrGsl field. </summary>
		public System.String UccrGsl { get; set;}
		/// <summary>Gets or sets the UccrGst field. </summary>
		public System.String UccrGst { get; set;}
		/// <summary>Gets or sets the UccrId field. </summary>
		public System.Int32 UccrId { get; set;}
		/// <summary>Gets or sets the UccrInsuranceId field. </summary>
		public Nullable<System.Int32> UccrInsuranceId { get; set;}
		/// <summary>Gets or sets the UccrInternal field. </summary>
		public System.Boolean UccrInternal { get; set;}
		/// <summary>Gets or sets the UccrKinAdd field. </summary>
		public System.String UccrKinAdd { get; set;}
		/// <summary>Gets or sets the UccrKinName field. </summary>
		public System.String UccrKinName { get; set;}
		/// <summary>Gets or sets the UccrKinRelationship field. </summary>
		public System.String UccrKinRelationship { get; set;}
		/// <summary>Gets or sets the UccrKinTel field. </summary>
		public System.String UccrKinTel { get; set;}
		/// <summary>Gets or sets the UccrLate field. </summary>
		public Nullable<System.Int32> UccrLate { get; set;}
		/// <summary>Gets or sets the UccrMobile field. </summary>
		public System.String UccrMobile { get; set;}
		/// <summary>Gets or sets the UccrName field. </summary>
		public System.String UccrName { get; set;}
		/// <summary>Gets or sets the UccrNotes field. </summary>
		public System.String UccrNotes { get; set;}
		/// <summary>Gets or sets the UccrPagerId field. </summary>
		public Nullable<System.Double> UccrPagerId { get; set;}
		/// <summary>Gets or sets the UccrPagerSerial field. </summary>
		public System.String UccrPagerSerial { get; set;}
		/// <summary>Gets or sets the UccrPassword field. </summary>
		public System.String UccrPassword { get; set;}
		/// <summary>Gets or sets the UccrPercentage field. </summary>
		public Nullable<System.Double> UccrPercentage { get; set;}
		/// <summary>Gets or sets the UccrPicturePath field. </summary>
		public System.String UccrPicturePath { get; set;}
		/// <summary>Gets or sets the UccrPolicyNo field. </summary>
		public System.String UccrPolicyNo { get; set;}
		/// <summary>Gets or sets the UccrProfile field. </summary>
		public System.String UccrProfile { get; set;}
		/// <summary>Gets or sets the UccrPublicLiabilityId field. </summary>
		public Nullable<System.Int32> UccrPublicLiabilityId { get; set;}
		/// <summary>Gets or sets the UccrReg field. </summary>
		public System.String UccrReg { get; set;}
		/// <summary>Gets or sets the UccrRt field. </summary>
		public System.String UccrRt { get; set;}
		/// <summary>Gets or sets the UccrRtaddress field. </summary>
		public System.String UccrRtaddress { get; set;}
		/// <summary>Gets or sets the UccrSecurityDate field. </summary>
		public Nullable<System.DateTime> UccrSecurityDate { get; set;}
		/// <summary>Gets or sets the UccrShowClientPh field. </summary>
		public System.Boolean UccrShowClientPh { get; set;}
		/// <summary>Gets or sets the UccrStartDate field. </summary>
		public Nullable<System.DateTime> UccrStartDate { get; set;}
		/// <summary>Gets or sets the UccrSurname field. </summary>
		public System.String UccrSurname { get; set;}
		/// <summary>Gets or sets the UccrTeam field. </summary>
		public Nullable<System.Int32> UccrTeam { get; set;}
		/// <summary>Gets or sets the UccrTel field. </summary>
		public System.String UccrTel { get; set;}
		/// <summary>Gets or sets the UccrVehicle field. </summary>
		public System.String UccrVehicle { get; set;}
		/// <summary>Gets or sets the UccrVehicleMakeId field. </summary>
		public Nullable<System.Int32> UccrVehicleMakeId { get; set;}
		/// <summary>Gets or sets the UccrVehicleModel field. </summary>
		public System.String UccrVehicleModel { get; set;}
		/// <summary>Gets or sets the UccrVehicleYear field. </summary>
		public Nullable<System.Int32> UccrVehicleYear { get; set;}
		/// <summary>Gets or sets the UccrWebEnabled field. </summary>
		public System.Boolean UccrWebEnabled { get; set;}
		/// <summary>Gets or sets the VehicleMakeId field. </summary>
		public Nullable<System.Int32> VehicleMakeId { get; set;}
		/// <summary>Gets or sets the VehicleModel field. </summary>
		public System.String VehicleModel { get; set;}
		/// <summary>Gets or sets the VehicleRegistrationNumber field. </summary>
		public System.String VehicleRegistrationNumber { get; set;}
		/// <summary>Gets or sets the VehicleType field. </summary>
		public System.String VehicleType { get; set;}
		/// <summary>Gets or sets the VehicleYear field. </summary>
		public Nullable<System.Int32> VehicleYear { get; set;}
		/// <summary>Gets or sets the VodafoneNetwork field. </summary>
		public System.Boolean VodafoneNetwork { get; set;}
		/// <summary>Gets or sets the WebEnabled field. </summary>
		public System.Boolean WebEnabled { get; set;}
		/// <summary>Gets or sets the Width field. </summary>
		public Nullable<System.Double> Width { get; set;}
		/// <summary>Gets or sets the WithholdingTaxPercentage field. </summary>
		public Nullable<System.Decimal> WithholdingTaxPercentage { get; set;}
		/// <summary>Gets or sets the Wofexpiry field. </summary>
		public Nullable<System.DateTime> Wofexpiry { get; set;}
	}
}
