//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TblClientContactInternetPermission'.</summary>
	public partial class TblClientContactInternetPermission : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblClientContactInternetPermission"/> class.</summary>
		public TblClientContactInternetPermission() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the ClientContactId field. </summary>
		public System.Int32 ClientContactId { get; set;}
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the InternetPermissionId field. </summary>
		public System.Int32 InternetPermissionId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblClientContactInternetPermission.TblClientContact - TblClientContact.TblClientContactInternetPermissions (m:1)'</summary>
		public virtual TblClientContact TblClientContact { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblClientContactInternetPermission.TblInternetPermission - TblInternetPermission.TblClientContactInternetPermissions (m:1)'</summary>
		public virtual TblInternetPermission TblInternetPermission { get; set;}
	}
}
