//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TblDespatchView'.</summary>
	public partial class TblDespatchView : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblDespatchView"/> class.</summary>
		public TblDespatchView() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the DespatchViewId field. </summary>
		public System.Int32 DespatchViewId { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the Name field. </summary>
		public System.String Name { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the ShowOnAssistDespatch field. </summary>
		public Nullable<System.Boolean> ShowOnAssistDespatch { get; set;}
		/// <summary>Gets or sets the ShowOnDespatch field. </summary>
		public Nullable<System.Boolean> ShowOnDespatch { get; set;}
		/// <summary>Gets or sets the ShowOnJobFollowup field. </summary>
		public Nullable<System.Boolean> ShowOnJobFollowup { get; set;}
		/// <summary>Gets or sets the WhereCondition field. </summary>
		public System.String WhereCondition { get; set;}
	}
}
