//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TblInternetPermission'.</summary>
	public partial class TblInternetPermission : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblInternetPermission"/> class.</summary>
		public TblInternetPermission() : base()
		{
			this.TblClientContactInternetPermissions = new List<TblClientContactInternetPermission>();
			OnCreated();
		}

		/// <summary>Gets or sets the AssignToNewContacts field. </summary>
		public System.Boolean AssignToNewContacts { get; set;}
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the HideWhenInactive field. </summary>
		public System.Boolean HideWhenInactive { get; set;}
		/// <summary>Gets or sets the InternetPermissionId field. </summary>
		public System.Int32 InternetPermissionId { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the Name field. </summary>
		public System.String Name { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the SystemName field. </summary>
		public System.String SystemName { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblClientContactInternetPermission.TblInternetPermission - TblInternetPermission.TblClientContactInternetPermissions (m:1)'</summary>
		public virtual List<TblClientContactInternetPermission> TblClientContactInternetPermissions { get; set;}
	}
}
