//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TblJobLeaveNotHome'.</summary>
	public partial class TblJobLeaveNotHome : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblJobLeaveNotHome"/> class.</summary>
		public TblJobLeaveNotHome() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AllowLeave field. </summary>
		public System.Boolean AllowLeave { get; set;}
		/// <summary>Gets or sets the Category field. </summary>
		public System.String Category { get; set;}
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the LeaveNotHomeId field. </summary>
		public System.Int32 LeaveNotHomeId { get; set;}
		/// <summary>Gets or sets the Name field. </summary>
		public System.String Name { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the RequireCourierNotes field. </summary>
		public System.Boolean RequireCourierNotes { get; set;}
		/// <summary>Gets or sets the Sequence field. </summary>
		public System.Int32 Sequence { get; set;}
		/// <summary>Gets or sets the Smsname field. </summary>
		public System.String Smsname { get; set;}
	}
}
