//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TblUndeliverableLocation'.</summary>
	public partial class TblUndeliverableLocation : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TblUndeliverableLocation"/> class.</summary>
		public TblUndeliverableLocation() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the JobTypeId field. </summary>
		public System.Int32 JobTypeId { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the Message field. </summary>
		public System.String Message { get; set;}
		/// <summary>Gets or sets the Name field. </summary>
		public System.String Name { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the Podname field. </summary>
		public System.String Podname { get; set;}
		/// <summary>Gets or sets the UndeliverableLocationId field. </summary>
		public System.Int32 UndeliverableLocationId { get; set;}
		/// <summary>Gets or sets the WebDeliveredTimeLabel field. </summary>
		public System.String WebDeliveredTimeLabel { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblUndeliverableLocation.TucJobType - TucJobType.TblUndeliverableLocations (m:1)'</summary>
		public virtual TucJobType TucJobType { get; set;}
	}
}
