//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TucEvent'.</summary>
	public partial class TucEvent : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TucEvent"/> class.</summary>
		public TucEvent() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the SpeedId field. </summary>
		public Nullable<System.Int32> SpeedId { get; set;}
		/// <summary>Gets or sets the UcevClientId field. </summary>
		public Nullable<System.Int32> UcevClientId { get; set;}
		/// <summary>Gets or sets the UcevClosed field. </summary>
		public System.Boolean UcevClosed { get; set;}
		/// <summary>Gets or sets the UcevContact field. </summary>
		public System.String UcevContact { get; set;}
		/// <summary>Gets or sets the UcevCourierId field. </summary>
		public Nullable<System.Int32> UcevCourierId { get; set;}
		/// <summary>Gets or sets the UcevDate field. </summary>
		public Nullable<System.DateTime> UcevDate { get; set;}
		/// <summary>Gets or sets the UcevDescription field. </summary>
		public System.String UcevDescription { get; set;}
		/// <summary>Gets or sets the UcevDespatcher field. </summary>
		public System.String UcevDespatcher { get; set;}
		/// <summary>Gets or sets the UcevEtatime field. </summary>
		public Nullable<System.DateTime> UcevEtatime { get; set;}
		/// <summary>Gets or sets the UcevId field. </summary>
		public System.Int32 UcevId { get; set;}
		/// <summary>Gets or sets the UcevJobId field. </summary>
		public Nullable<System.Int32> UcevJobId { get; set;}
		/// <summary>Gets or sets the UcevJobNumber field. </summary>
		public System.String UcevJobNumber { get; set;}
		/// <summary>Gets or sets the UcevJobType field. </summary>
		public Nullable<System.Int32> UcevJobType { get; set;}
		/// <summary>Gets or sets the UcevLateTime field. </summary>
		public Nullable<System.Double> UcevLateTime { get; set;}
		/// <summary>Gets or sets the UcevNotes field. </summary>
		public System.String UcevNotes { get; set;}
		/// <summary>Gets or sets the UcevOriginator field. </summary>
		public Nullable<System.Int32> UcevOriginator { get; set;}
		/// <summary>Gets or sets the UcevPageCourier field. </summary>
		public System.Boolean UcevPageCourier { get; set;}
		/// <summary>Gets or sets the UcevResponseTime field. </summary>
		public Nullable<System.DateTime> UcevResponseTime { get; set;}
		/// <summary>Gets or sets the UcevStaffIdin field. </summary>
		public Nullable<System.Double> UcevStaffIdin { get; set;}
		/// <summary>Gets or sets the UcevStaffIdout field. </summary>
		public Nullable<System.Double> UcevStaffIdout { get; set;}
		/// <summary>Gets or sets the UcevTime field. </summary>
		public Nullable<System.DateTime> UcevTime { get; set;}
		/// <summary>Gets or sets the UcevType field. </summary>
		public Nullable<System.Double> UcevType { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TucEvent.TucClient - TucClient.TucEvents (m:1)'</summary>
		public virtual TucClient TucClient { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TucEvent.TucJobType - TucJobType.TucEvents (m:1)'</summary>
		public virtual TucJobType TucJobType { get; set;}
	}
}
