//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TucJobItem'.</summary>
	public partial class TucJobItem : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TucJobItem"/> class.</summary>
		public TucJobItem() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Depth field. </summary>
		public System.Double Depth { get; set;}
		/// <summary>Gets or sets the Dgclass field. </summary>
		public Nullable<System.Int32> Dgclass { get; set;}
		/// <summary>Gets or sets the Do field. </summary>
		public Nullable<System.Boolean> Do { get; set;}
		/// <summary>Gets or sets the Height field. </summary>
		public System.Double Height { get; set;}
		/// <summary>Gets or sets the ItemId field. </summary>
		public System.Int32 ItemId { get; set;}
		/// <summary>Gets or sets the Items field. </summary>
		public System.Int32 Items { get; set;}
		/// <summary>Gets or sets the JobId field. </summary>
		public System.Int32 JobId { get; set;}
		/// <summary>Gets or sets the Length field. </summary>
		public System.Double Length { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the Pu field. </summary>
		public Nullable<System.Boolean> Pu { get; set;}
		/// <summary>Gets or sets the Weight field. </summary>
		public System.Double Weight { get; set;}
	}
}
