//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TucJobStatus'.</summary>
	public partial class TucJobStatus : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TucJobStatus"/> class.</summary>
		public TucJobStatus() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the UcjsCode field. </summary>
		public System.String UcjsCode { get; set;}
		/// <summary>Gets or sets the UcjsId field. </summary>
		public System.Int32 UcjsId { get; set;}
		/// <summary>Gets or sets the UcjsName field. </summary>
		public System.String UcjsName { get; set;}
		/// <summary>Gets or sets the UcjsReplyCode field. </summary>
		public System.String UcjsReplyCode { get; set;}
	}
}
