//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TucJobType'.</summary>
	public partial class TucJobType : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TucJobType"/> class.</summary>
		public TucJobType() : base()
		{
			this.TblUndeliverableLocations = new List<TblUndeliverableLocation>();
			this.TucEvents = new List<TucEvent>();
			OnCreated();
		}

		/// <summary>Gets or sets the AddonPercentage field. </summary>
		public Nullable<System.Decimal> AddonPercentage { get; set;}
		/// <summary>Gets or sets the Alias field. </summary>
		public System.String Alias { get; set;}
		/// <summary>Gets or sets the CourierPercentage field. </summary>
		public Nullable<System.Decimal> CourierPercentage { get; set;}
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the DatacomEntry field. </summary>
		public System.Boolean DatacomEntry { get; set;}
		/// <summary>Gets or sets the DeliveryMargin field. </summary>
		public Nullable<System.Int32> DeliveryMargin { get; set;}
		/// <summary>Gets or sets the DeliveryTime field. </summary>
		public Nullable<System.Int32> DeliveryTime { get; set;}
		/// <summary>Gets or sets the ExtraName field. </summary>
		public System.String ExtraName { get; set;}
		/// <summary>Gets or sets the JobEntry field. </summary>
		public System.Boolean JobEntry { get; set;}
		/// <summary>Gets or sets the JobLetter field. </summary>
		public System.String JobLetter { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the Minutes field. </summary>
		public Nullable<System.Int32> Minutes { get; set;}
		/// <summary>Gets or sets the NationwideEntry field. </summary>
		public System.Boolean NationwideEntry { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the PickupTime field. </summary>
		public Nullable<System.Int32> PickupTime { get; set;}
		/// <summary>Gets or sets the ServiceTrackingId field. </summary>
		public Nullable<System.Int32> ServiceTrackingId { get; set;}
		/// <summary>Gets or sets the ShortName field. </summary>
		public System.String ShortName { get; set;}
		/// <summary>Gets or sets the SplitJobDeliveryTime field. </summary>
		public Nullable<System.Int32> SplitJobDeliveryTime { get; set;}
		/// <summary>Gets or sets the SuccessRate field. </summary>
		public Nullable<System.Decimal> SuccessRate { get; set;}
		/// <summary>Gets or sets the SystemName field. </summary>
		public System.String SystemName { get; set;}
		/// <summary>Gets or sets the TruckJobEntry field. </summary>
		public Nullable<System.Boolean> TruckJobEntry { get; set;}
		/// <summary>Gets or sets the UcjtBaseRate field. </summary>
		public System.Decimal UcjtBaseRate { get; set;}
		/// <summary>Gets or sets the UcjtCode field. </summary>
		public System.String UcjtCode { get; set;}
		/// <summary>Gets or sets the UcjtDescription field. </summary>
		public System.String UcjtDescription { get; set;}
		/// <summary>Gets or sets the UcjtId field. </summary>
		public System.Int32 UcjtId { get; set;}
		/// <summary>Gets or sets the UcjtName field. </summary>
		public System.String UcjtName { get; set;}
		/// <summary>Gets or sets the UcjtUnitRate field. </summary>
		public System.Decimal UcjtUnitRate { get; set;}
		/// <summary>Gets or sets the WebJobEntry field. </summary>
		public System.Boolean WebJobEntry { get; set;}
		/// <summary>Gets or sets the WebServiceEntry field. </summary>
		public System.Boolean WebServiceEntry { get; set;}
		/// <summary>Gets or sets the ZoneRated field. </summary>
		public Nullable<System.Boolean> ZoneRated { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TblUndeliverableLocation.TucJobType - TucJobType.TblUndeliverableLocations (m:1)'</summary>
		public virtual List<TblUndeliverableLocation> TblUndeliverableLocations { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TucEvent.TucJobType - TucJobType.TucEvents (m:1)'</summary>
		public virtual List<TucEvent> TucEvents { get; set;}
	}
}
