//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DespatchWeb.EntityClasses
{
	/// <summary>Class which represents the entity 'TucSuburb'.</summary>
	public partial class TucSuburb : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="TucSuburb"/> class.</summary>
		public TucSuburb() : base()
		{
			this.TucClients = new List<TucClient>();
			OnCreated();
		}

		/// <summary>Gets or sets the AirportId field. </summary>
		public Nullable<System.Int32> AirportId { get; set;}
		/// <summary>Gets or sets the AirportKm field. </summary>
		public Nullable<System.Int32> AirportKm { get; set;}
		/// <summary>Gets or sets the Alias field. </summary>
		public System.String Alias { get; set;}
		/// <summary>Gets or sets the BaggageArea field. </summary>
		public Nullable<System.Int32> BaggageArea { get; set;}
		/// <summary>Gets or sets the City field. </summary>
		public System.String City { get; set;}
		/// <summary>Gets or sets the Created field. </summary>
		public System.DateTime Created { get; set;}
		/// <summary>Gets or sets the CreatedBy field. </summary>
		public System.String CreatedBy { get; set;}
		/// <summary>Gets or sets the DeliveryStandardId field. </summary>
		public Nullable<System.Int32> DeliveryStandardId { get; set;}
		/// <summary>Gets or sets the FreightForwardAmount field. </summary>
		public Nullable<System.Decimal> FreightForwardAmount { get; set;}
		/// <summary>Gets or sets the GoogleSuburbAlias field. </summary>
		public System.String GoogleSuburbAlias { get; set;}
		/// <summary>Gets or sets the Gsscity field. </summary>
		public System.String Gsscity { get; set;}
		/// <summary>Gets or sets the Gsssuburb field. </summary>
		public System.String Gsssuburb { get; set;}
		/// <summary>Gets or sets the LastModified field. </summary>
		public System.DateTime LastModified { get; set;}
		/// <summary>Gets or sets the LastModifiedBy field. </summary>
		public System.String LastModifiedBy { get; set;}
		/// <summary>Gets or sets the OurRefCode field. </summary>
		public System.String OurRefCode { get; set;}
		/// <summary>Gets or sets the PostCode field. </summary>
		public System.String PostCode { get; set;}
		/// <summary>Gets or sets the PrefixRunName field. </summary>
		public System.String PrefixRunName { get; set;}
		/// <summary>Gets or sets the Priority field. </summary>
		public Nullable<System.Int32> Priority { get; set;}
		/// <summary>Gets or sets the SamedayRegion field. </summary>
		public Nullable<System.Int32> SamedayRegion { get; set;}
		/// <summary>Gets or sets the Sdamount field. </summary>
		public Nullable<System.Decimal> Sdamount { get; set;}
		/// <summary>Gets or sets the SdrawAmount field. </summary>
		public Nullable<System.Decimal> SdrawAmount { get; set;}
		/// <summary>Gets or sets the SiteId field. </summary>
		public Nullable<System.Int32> SiteId { get; set;}
		/// <summary>Gets or sets the Smsname field. </summary>
		public System.String Smsname { get; set;}
		/// <summary>Gets or sets the UcsuArea field. </summary>
		public System.Int32 UcsuArea { get; set;}
		/// <summary>Gets or sets the UcsuBaseRegion field. </summary>
		public System.Int32 UcsuBaseRegion { get; set;}
		/// <summary>Gets or sets the UcsuId field. </summary>
		public System.Int32 UcsuId { get; set;}
		/// <summary>Gets or sets the UcsuKm field. </summary>
		public Nullable<System.Int32> UcsuKm { get; set;}
		/// <summary>Gets or sets the UcsuName field. </summary>
		public System.String UcsuName { get; set;}
		/// <summary>Gets or sets the UcsuRegion field. </summary>
		public Nullable<System.Int32> UcsuRegion { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'TucClient.TucSuburb - TucSuburb.TucClients (m:1)'</summary>
		public virtual List<TucClient> TucClients { get; set;}
	}
}
